### ISSUE TITLE
Message action menu on hover

### ISSUE THREAD

**Issue by ryanalexander** [revoltchat/revite#101]
**Suggested by AM (01FDAGS998CB2B0HSGK8DHK8NP) in Suggestions on Revolt server**

Show a quick action overlay in top-right of the message box with

- Quick Reply
- React (When implemented)
- Edit (If sent by user)
- Delete (If sent by user, or delete message perm is granted)
- 
-- Show when holding shift
- Copy id (If developer mode is enabled)
- Copy link

**Comment by Rexogamer** [comment]
Partially added in #493.

**Comment by kuhnchris** [comment]
With #493 it's very easy to implement additional buttons:
![image](https://user-images.githubusercontent.com/761911/148609511-7521013e-f207-4b9b-a25d-03969047b05e.png)
Just throw in the additional overlaybuttons with the functions (easiest to just copy them from the contextmenu.tsx) and it's done. (for the non-shift menu)

**Comment by kuhnchris** [comment]
i actually implemented that for #493 now (the edit and delete own posts if message.author == user) - for shift-style menu I'd need an example how you'd like to have it.

**Comment by insertish** [comment]
Closing issue as it was implemented.
