### ISSUE TITLE
bug: The Server Is down!

### ISSUE THREAD

**Issue by Diabulus1** [revoltchat/revite#1040]
### What happened?

always connected and disconnected, and i am always off(
Please explain, maybe are you working with Servers?

### Branch

Production (app.revolt.chat)

### Commit hash

Servers is down.

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Not an issue with revite.
