### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by MrANANAS1** [revoltchat/revite#1044]
### What happened?

I downloaded the Revolt app, but when I called a friend, the sound did not turn on, then I went into the settings, put it there, then went out and did not work again, then went back into the settings, put the speaker and microphone out again, did not work, then went back in and I see that it was reset again where the speaker and microphone help solve the problem

### Branch

Production (app.revolt.chat)

### Commit hash

I downloaded the Revolt app, but when I called a friend, the sound did not turn on, then I went into the settings, put it there, then went out and did not work again, then went back into the settings, put the speaker and microphone out again, did not work, then went back in and I see that it was reset again where the speaker and microphone help solve the problem

### Relevant log output

I downloaded the Revolt app, but when I called a friend, the sound did not turn on, then I went into the settings, put it there, then went out and did not work again, then went back into the settings, put the speaker and microphone out again, did not work, then went back in and I see that it was reset again where the speaker and microphone help solve the problem

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [x] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment]
im gonna assume this was posted twice (#1043) in error.
