### ISSUE TITLE
bug: media files cannot be sent

### ISSUE THREAD

**Issue by MyraLejean** [revoltchat/revite#1053]
### What happened?

when trying to send a media file, a "database error" occurs
the same error occurs in the mobile version

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

Nightly 1.0.1
API: 0.7.14
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by DeclanChidlow** [comment]
This was due to an Autumn outage. Resolved now.
