### ISSUE TITLE
Cursor randomly jumps to the end of the text while typing

### ISSUE THREAD

**Issue by ekhsdee** [revoltchat/revite#107]
https://user-images.githubusercontent.com/88977599/129923649-a7f55bbe-48e3-4254-9f76-d24ef73ef054.mp4

Can be reproduced in Firefox and Linux App but couldn't do on mobile version.

**Comment by jack1142** [comment]
This seems like a duplicate of #54

**Comment by insertish** [comment]
Closing in favor of #54
