### ISSUE TITLE
Typing bar cuts into scrollbar

### ISSUE THREAD

**Issue by meizuflux** [revoltchat/revite#109]
![image](https://user-images.githubusercontent.com/76911441/129926500-70e6d391-7e42-4887-8269-697bd41fc812.png)
it should probably stop at the scrollbar. 

Specs: 
Firefox

**Comment by ryanalexander** [comment]
Confirmed.

Indicator on who is typing is above the scrollbar

**Comment by insertish** [comment]
I just went over the code, also added new internal variables on a387d3c6aedab343a966018060d640364bb03f8e, what version of Firefox are you using?
Because this works on both latest FF and Chrome.
