### ISSUE TITLE
banner / avatar wont remove on profile page

### ISSUE THREAD

**Issue by tobggs** [revoltchat/revite#110]
https://gyazo.com/9b6458c166407408a9b65055b5602c84

**Comment by ryanalexander** [comment]
Have you tried clicking save at the bottom?

**Comment by tobggs** [comment]
> Have you tried clicking save at the bottom?

it doesnt work to press save button btw, it automatically saves.

**Comment by ryanalexander** [comment]
Seems like a visual issue. The profile / custom background is removed but the element is not updated.
