### ISSUE TITLE
Mobile detection fails on the DDG android browser

### ISSUE THREAD

**Issue by Jan0660** [revoltchat/revite#113]

**Comment by insertish** [comment]
Reproduced, DDG is likely hiding information about the browser from us :/

![image](https://user-images.githubusercontent.com/38285861/130434707-912da794-b047-444a-8090-dbc6a6d977d6.png)

![image](https://user-images.githubusercontent.com/38285861/130434714-1660e9bf-0481-4650-a367-bb14663b3b3f.png)

**Comment by Rexogamer** [comment]
Just out of curiosity, can someone share DDGB's user agent? There might be something useable there.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
