### ISSUE TITLE
Badges do not indicate consistently if they are clickable or not via the mouse cursor.

### ISSUE THREAD

**Issue by ehea617** [revoltchat/revite#122]
### Summary
The Supporter badge does not change the mouse cursor to indicate that the badge is clickable. The Developer and Early Adopter badges do not link anywhere but shows the pointer indicating that they are clickable.

### Steps to Reproduce

1. Open a profile with some badges.
2. Notice that cursor behavior is not consistent with the various badges. See test results below:

### Badge Testing Results

| Badge  | Results |
| ------------- | ------------- |
| Developer badge  | Does not link to any page but shows cursor indicating clickable  |
| Translator badge  |  Behavior working as intended |
| Supporter badge  | Links to https://insrt.uk/donate but does not show cursor indicating clickable |
| Responsible Disclosure badge  | Behavior working as intended  |
| Early Adopter badge  | Does not link to any page but shows cursor indicating clickable  |

**Comment by ryanalexander** [comment]
Fixed in https://github.com/revoltchat/revite/commit/bde8b58095ff858a51d87aede61190279f433144
