### ISSUE TITLE
The message date has its first letter not capitalized (at least in French)

### ISSUE THREAD

**Issue by 4rnoP** [revoltchat/revite#126]
The first letter of the string indicating the date of a message is not capitalized, for example "mardi dernier à HH:MM" (Last Tuesday at HH:MM). The issue is that the first part of the string (indicating the day of the week) is rendered by dayjs.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
