### ISSUE TITLE
Don't render empty context menus.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#13]
Don't render a context menu if the returned array is empty.

**Comment by fatalerrorcoded** [comment]
Fixed in [preact-context-menu 0.2.1](https://www.npmjs.com/package/preact-context-menu/v/0.2.1)

**Comment by insertish** [comment]
Re-opened this issue in cb63cf0d9243db7aa2cd7ab226e18f7ee23b53f3.
Commit 882545294296995e6d0870a8889afcdc28677426 would prevent nightly.revolt.chat from functioning.

**Comment by insertish** [comment]
Once again, fixed in 899593faf08622991ed1dbd64887d80311d71218.
Now it works for real.

**Comment by insertish** [comment]
Some technical details:
Vite didn't like some relative imports in revolt.js, so the entire thing was pretty unstable.
