### ISSUE TITLE
Weird scrollbars on parts of the web application.

### ISSUE THREAD

**Issue by snthcy** [revoltchat/revite#133]
![image](https://user-images.githubusercontent.com/47870580/130367917-6fd8b71f-1fb8-46af-9692-a3ac45579cab.png)

Slider is on the server list and it doesn't look too good. Not too sure if this is intentional.

**Comment by ryanalexander** [comment]
What browser are you using?

**Comment by insertish** [comment]
From picture, it's probably due to vertical scrollbar.
Need browser version too, will close since this isn't an issue on latest Chrome / FF.

Feel free to re-open if it is still an issue.

**Comment by Rexogamer** [comment]
Insert never closed this, so I shall instead - if this is still an issue, as per above, feel free to reopen with more info.

**Comment by snthcy** [comment]
Yeah, sorry I totally forgot about this... for 4 months! It appears to not be an issue anymore, I was also on the latest Firefox version at the time, anyways thank you and Merry Christmas :))
