### ISSUE TITLE
Clicking "Reply" on a deleted message adds an invalid message to the replying section

### ISSUE THREAD

**Issue by TaiAurori** [revoltchat/revite#143]
When attempting to add a reply to the chatbox for a message that's been deleted (i.e the moment the "Reply" option is clicked in the context menu, someone deletes the message), Revite will try to load the message to display above the chatbox. However, because the message is deleted, it results in a placeholder "Couldn't load message" to appear instead.
![image](https://user-images.githubusercontent.com/31465218/130852215-ab47d170-b7c4-41a6-865c-e31b1783cc7a.png)

**Comment by geshii** [comment]
> IMO I think a more preferable solution would be to show something along the lines of "Deleted message" instead of a placeholder error. Not to mention that sending a message outright fails when one of the replies are deleted.

I see, I'll try to find a fix for that soon

**Comment by insertish** [comment]
I think the reply bar could probably just listen to changes and if it disappears / 404s then it can eject itself.
