### ISSUE TITLE
Topic popup not disappearing when clicking a Revolt webapp link.

### ISSUE THREAD

**Issue by lambdagg** [revoltchat/revite#144]
When, for example, clicking on the **/settings/feedback** link on the **app.revolt.gay/Testers** server, the topic popup stays open and avoids the user from clicking anywhere else. The expected behavior is to only close the popup when the link redirects to the same page, I think?

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
