### ISSUE TITLE
Provide consistent class names for themes.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#149]
Class names are currently generated by:
- `styled-components`, which are super inconsistent
- `Vite` which should stay fairly consistent, but unsure of how reliable they are

Need a nice way to provide consistent class names to people who want to theme the app.

**Comment by Bawbby** [comment]
No idea what I'm doing but I looked into doing consistent class names.
- Vite uses `postcss-modules` for the CSS module class names. You can configure with `css.modules.generatedScopeName`
- For Styled components it looks impossible. Styled components generate random class names to prevent name clashing.

Let me know if I got anything wrong though.

**Comment by philip-peterson** [comment]
Styled-components provides support for themeing -- https://styled-components.com/docs/api#themeprovider it's just a little more specific than creating a raw stylesheet.

**Comment by insertish** [comment]
Unintentionally fixed this in 3fd56e4fdcdfc57f947656764e465e1b8c3f08a0.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/38285861/149586014-888d86dc-f7a2-4fe1-9b57-a71d1ef61359.png">
