### ISSUE TITLE
The problem of entering twice in Korean

### ISSUE THREAD

**Issue by emptycan1010** [revoltchat/revite#153]
When I press 안녕하세요. In Revolt, it types 안녕하세세요
![ezgif com-gif-maker](https://user-images.githubusercontent.com/85441644/131249248-adcbafbe-10f8-4f9b-ba7b-cbf0aff1280d.gif)
This gives me terrible experience

**Comment by insertish** [comment]
Likely related to #54, keeping both opening just in case.

**Comment by insertish** [comment]
Potentially fixed in d368820aeb0e6106a064acd35adb186a4cbc2f5d, you can test it on https://nightly.revolt.chat

**Comment by insertish** [comment]
Ok, it was also pushed to production, please let me know if that fixes it.
