### ISSUE TITLE
Resizable UI Elements/Columns (Enhancement Request)

### ISSUE THREAD

**Issue by mattgphoto** [revoltchat/revite#160]
One common thing that's been a request for years in other chat applications is resizable columns, as that's the item that typically eats up so much screen space, and resizing columns like Channel list or Members List would help dramatically.

**Comment by Steveplays28** [comment]
Working on this right now 🙂 
See this branch in my fork of Revite: https://github.com/Steveplays28/revite/tree/sidebar-resizing

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
