### ISSUE TITLE
Deafen and mute buttons are a bit glitchy.

### ISSUE THREAD

**Issue by DillFrescott** [revoltchat/revite#163]
Sometimes you have to click one to toggle the other or something like that.

Basically I'm trying to say it's glitchy lol.

**Comment by Nicklarose** [comment]
In my experience:

-Clicking Mute Microphone works properly every time
-Clicking Deafen does deafen the sound, but the red Deafen symbol is not present which makes it hard to tell the state you are in. If you then click Mute Microphone after clicking Deafen, it updates and shows the Deafen symbol
-Clicking Deafen two or more times will only change the state of Deafen 1 time. To change state of Deafen again you will have to mute/unmute.

**Comment by insertish** [comment]
Duplicate / related to #89 which in turn is blocked on the voice rewrite.
