### ISSUE TITLE
it has a bug when i use korean

### ISSUE THREAD

**Issue by ajb3296** [revoltchat/revite#164]
![스크린샷 2021-08-31 오전 8 21 18](https://user-images.githubusercontent.com/33373557/131417998-08703813-f6f3-45f9-ba8d-a5167fa3eae2.png)
like this
the last letter is sent twice

**Comment by KeepSOBP** [comment]
#153 duplicate

**Comment by ajb3296** [comment]
> #153 duplicate 

it is another bug

**Comment by insertish** [comment]
Is there anyway I could re-produce this? I could try simulating entering the text, I just need the string.

**Comment by ajb3296** [comment]
yes, Try with "안녕하세요"

**Comment by ajb3296** [comment]
https://user-images.githubusercontent.com/33373557/131476101-ed802f58-30f1-4596-9eab-f74de4ac8a6b.mp4
