### ISSUE TITLE
Colours on embeds not rendering.

### ISSUE THREAD

**Issue by kaylynnnn** [revoltchat/revite#166]
Colours are not renderring on the client, I've tested on the web app and on the desktop client found in this orginisation's repositories.

![The colour not showing](https://i.imgur.com/VG7lpl1.png)

![The properties of the embed](https://i.imgur.com/WbVBvEq.png)

As you can see the embed is supposed to have a colour but it doesn't show.

**Comment by janderedev** [comment]
Not sure what's going on here, but this appears to be an issue with january (image + embed proxy).

From inspecting the WebSocket messages, it doesn't appear as if the client ever receives the `colour` field:
![image](https://user-images.githubusercontent.com/26145882/140997240-00df1608-8eb5-4821-b6b2-85b9cd5ab514.png)

I don't have enough experience with Rust and january to fix this issue right now, someone else should take a look at this.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
