### ISSUE TITLE
Implement new server identity modal

### ISSUE THREAD

**Issue by infi** [revoltchat/revite#172]
![image](https://user-images.githubusercontent.com/45950794/131731154-8ae0f9b7-f5ab-4679-965b-52f9a8e22bed.png)

**Comment by infi** [comment]
Only the nickname. The avatar is saved automatically as it happens everywhere else in the app.

**Comment by insertish** [comment]
Requires #333

**Comment by insertish** [comment]
![image](https://user-images.githubusercontent.com/38285861/174443904-0fa00b53-ebe0-4d01-90bc-90b56d7114a0.png)
