### ISSUE TITLE
Add a way to delete accounts in-app.

### ISSUE THREAD

**Issue by ghost** [revoltchat/revite#183]
Hello,

I was fooling around with the web app, trying different buttons to see if anything went wrong, and it appears that the "Delete account" option doesn't work or accomplishes anything. I tried searching the bug tracker to see whether the issue was known, but I couldn't find anything. I'm only marking this as a problem to be resolved; I have no plans to leave the platform. ;)

In any event, if the problem is already known, you are welcome to respond or simply close my post.

**Comment by insertish** [comment]
Right now the intended behaviour is that it opens your mail client to send a deletion request, this is going to be changed in the future likely with https://github.com/revoltchat/delta/issues/63, but I'm wondering why it didn't work here.

Can you give me any more details about your browser and system?

**Comment by t0tev** [comment]
In a customized Windows 10 Pro ISO, I'm running the Brave browser with enhanced security features to hide my fingerprint and prevent tracking. The system shouldn't be interfering with the web app itself, and I also tested it with the standard Chrome browser, but it didn't open anything. It's conceivable that it doesn't recognize the email client that I used to set up the account.

**Comment by Rexogamer** [comment]
With RAuth v1 since adopted, I'm a little confused - what work is left to be done? (I assume some Delta changes are involved.)

**Comment by insertish** [comment]
Need to add routes for wiping account data.

**Comment by insertish** [comment]
this exists
