### ISSUE TITLE
504: GATEWAY_TIMEOUT 

### ISSUE THREAD

**Issue by HorizonCookie** [revoltchat/revite#187]
When I try to join the beta via the homepage by pressing the ”Join Public Beta” and following the button ”Continue”, I get this result.
Same goes with iPhone and Google Chrome on PC. 
I don’t have an account nor an invitation code for making an account.

Need any details to solve it? Lemme know.

![EDCB3F48-F91D-469D-A6A0-0E9EC45318B2](https://user-images.githubusercontent.com/15304488/132137101-17ce3164-5b42-4c6b-bacf-a61bed8f4060.png)

**Comment by HorizonCookie** [comment]
Seems like it solved itself? I managed to join through phone and PC.

**Comment by insertish** [comment]
Yep, I forgot to update an address after migrating the server yesterday.
