### ISSUE TITLE
App badges for mentions.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#19]
Show an application badge (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge) when the user has been mentioned in a server.

**Comment by kuhnchris** [comment]
Is the scope right now just for mentions in servers, or also DMs?

**Comment by kuhnchris** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Badging_API
Bad browser support right now, postponed

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
