### ISSUE TITLE
Can't access browser spellcheck when editing a message

### ISSUE THREAD

**Issue by gregorypappas** [revoltchat/revite#193]
![image](https://user-images.githubusercontent.com/47937456/132294994-8e30582f-2074-4e9f-812b-6ae4d43286ae.png)

This can be worked around by holding shift then right-clicking but I don't believe every browser has this feature.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
