### ISSUE TITLE
Switching between servers and dms does not retain state for Home and Friends tab

### ISSUE THREAD

**Issue by skybird23333** [revoltchat/revite#195]
When clicking on a DM channel, then clicking on a server and back the client automatically jumps to the last open DM channel. This does not apply to the Home and Friends tab. When a DM channel is clicked on and then clicking on Home/Friends before going to a server and back the client will jump to the DM channel.

This does apply to the notes channel.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
