### ISSUE TITLE
Navigating directly to settings from outside the client then exiting will return user to previous page

### ISSUE THREAD

**Issue by gregorypappas** [revoltchat/revite#201]
Is this intended behavior? Legitimately torn on this. Could be considered correct by some but I was personally expecting it to go to the Home tab.

https://user-images.githubusercontent.com/47937456/132357298-5ba9f04a-f95d-4eec-86e0-6a2c644b1de6.mp4

**Comment by insertish** [comment]
Nevermind, I mis-understood the video.

**Comment by LedaThemis** [comment]
@insertish wasn't this fixed in [5a49bc7](https://github.com/revoltchat/revite/commit/5a49bc7d20ea9253c86caea96bdc1ef8e7a5cee2)?

**Comment by insertish** [comment]
Probably.
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
