### ISSUE TITLE
Emoji Resolution Menu not working when clicking AND editing message

### ISSUE THREAD

**Issue by cyrus01337** [revoltchat/revite#207]
Title says all, demonstration below:
![Demonstration](https://user-images.githubusercontent.com/63274991/132427817-8c4ab73b-bdec-437f-98fd-5fcddee6d5d9.gif)

### Specifications
Device name	PC
Processor	AMD Ryzen 3 3200G with Radeon Vega Graphics       3.60 GHz
Installed RAM	24.0 GB
Device ID	6F5A0795-210A-4F14-98E3-9DB6575AA81D
Product ID	00326-30000-00001-AA585
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Revolt
MS Store Client
eea13a3 (master)
Nightly 1.0.0-vite
Native: 1.0.0
API: 0.5.2-alpha.2
revolt.js: 5.0.1-alpha.6-patch.2

**Comment by LedaThemis** [comment]
No longer reproducible currently, and couldn't sign in from that client version

**Comment by cyrus01337** [comment]
Can assume it was fixed until reopened.
