### ISSUE TITLE
Empty lines issues

### ISSUE THREAD

**Issue by Andre601** [revoltchat/revite#214]
There are a few issues with empty lines which I want to list here real quick.

### 1) Empty lines in general are ignored
An input like
```markdown
Line 1

Line 2
```
will result to this
```markdown
Line 1

Line 2
```

A current "fix" is to use `\` in the empty line.

### 2) `\` won't work above headers, lists, etc
When using the aforementioned `\` trick above specific markdown formatting will the `\` not be hidden.

For example will
```markdown
Line 1
\
## Line 2
```
show as
```markdown
Line 1
\
Line 2
```
The same goes for lists and tables.

### 3) `----` is not displayed when used
When using `----` directly under a text will it render as header, which is understandable.

When you, however, add an empty line above it, will this empty line be rendered and the lines will be hidden.

For example will
```markdown
Line 1

----
Line 2
```
become
```markdown
Line 1

Line 2
```

This trick seems to also work above headers and alike.

**Comment by insertish** [comment]
Can we even fix this? Since markdown is offloaded to markdown-it.

**Comment by Andre601** [comment]
> Can we even fix this? Since markdown is offloaded to markdown-it.

I mean... If that was really an issue of the markdown render util or whatever, then it would probably be better to just switch it, because not supporting empty lines is beyond stupid to put it simple.
