### ISSUE TITLE
Mention toggle "on"/"off" string cannot be translated

### ISSUE THREAD

**Issue by Edward205** [revoltchat/revite#220]
Credit to stef (in revolt) for finding this
<img width="113" alt="Captură de ecran din 2021-09-10 la 23 21 52" src="https://user-images.githubusercontent.com/52004020/132913324-b4022406-106c-4cba-a3f0-d3394d26e11b.png">

**Comment by brecert** [comment]
Fixed in 806e3108cb7c24a672f2d6b44d9efe4e21f41a41
