### ISSUE TITLE
profile settings bugs

### ISSUE THREAD

**Issue by moonlincoder** [revoltchat/revite#226]
### as I assume, using Unicode characters in the password can cause these problems

bug when changing nickname:
![изображение](https://user-images.githubusercontent.com/62523761/132984041-ea910c33-afa9-4ac1-b146-7289a0480f9c.png)

bug when changing pass:
![изображение](https://user-images.githubusercontent.com/62523761/132983961-cafa3b30-b381-4f3b-837c-f29c2f0a0e24.png)

**Comment by LedaThemis** [comment]
this seems to be fixed?

I tried: "", "˅" (nickname)
and: "ʫʫʫʫʫʫʫʫ", "" (password)

and they all worked with no complaints.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
