### ISSUE TITLE
[BUG] Theme shop tab doesn’t appear/disappear instantly

### ISSUE THREAD

**Issue by killianeletellier** [revoltchat/revite#234]
**Bug description**
When you enable Theme Shop in the Experiments settings, the new settings tab doesn't appear instantly. 

**Reproduction steps**
1. Open settings 
2. Enter Experiments Tab
3. Enable Theme Shop

**Expected result**
The new Theme Shop tab appears instantly, when you enable it. 

**Current result**
The tab only appear when you will change tab. 

**Note**
This occurs when you disable the Experiment too.

**Comment by Rexogamer** [comment]
Can't seem to reproduce - is this still an issue? Bear in mind that a bunch of rewriting/reworking was done recently (we switched to MobX, which comes with various benefits), and this work did touch upon settings/experiments

**Comment by brecert** [comment]
> Can't seem to reproduce - is this still an issue? (A bunch of rewriting/reworking was done recently (we switched to MobX, which comes with various benefits), and this work did touch upon settings/experiments)

Indded, this was noted and fixed when switching to MobX.
