### ISSUE TITLE
在mac上面用注音輸入法的時候按enter完成片段字串的時候會自己送出

### ISSUE THREAD

**Issue by Sam20060720** [revoltchat/revite#239]
https://user-images.githubusercontent.com/40285756/133262237-be912e9e-beb4-48e1-abea-78eabd0b74ff.mov

**Comment by Sam20060720** [comment]
Usually in the middle of typing, the carriage return is used to confirm that the paragraph has been completed (no change), but when you press carriage return, it will automatically send the entire sentence, even if the entire sentence is not completed.

**Comment by brecert** [comment]
What OS are you using?

What input method are you using?
