### ISSUE TITLE
Audio settings immediately prompts for audio access.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#242]
We should show a prompt asking whether to ask for permission.

Something like "You need to grant permission to access audio settings." with a button below it to start grant flow.

From discussion: https://github.com/revoltchat/revolt/discussions/112

**Comment by DavidShefcik** [comment]
If you guys need help I can try taking a swing at this

**Comment by andy5995** [comment]
OS: Manjaro 21.2.6

Installed revolt-desktop from the AUR
