### ISSUE TITLE
Default image graphic showing up to the left of country flags

### ISSUE THREAD

**Issue by Frequential** [revoltchat/revite#247]
Under `Settings > Language`, we can see a "default missing image graphic" show up to the left of all the country flags as shown here: 
![image](https://user-images.githubusercontent.com/28309837/133431057-d1a5cabc-6dfe-46e3-9bf6-fe68ab6d2740.png)

This doesn't happen in the other options where no flags are shown:
![image](https://user-images.githubusercontent.com/28309837/133431297-88f4f322-2f7f-4219-be81-a98ca1cc4c3a.png)

The first unicode that defines the flag type might not be displaying correctly.
- **Version information**: 4b8ad44 (master), Nightly 1.0.0-vite, Native: 1.0.1, API: 0.5.3-alpha.1, revolt.js: 5.1.0-alpha.0
- **OS**: Manjaro Linux (Kernel: 5.10.61-1-MANJARO) under GNOME 40.
- **Release type**: AppImage

**Comment by insertish** [comment]
Going to close this in favor of #310 since I've already explained the issue there.
