### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [revoltchat/revite#248]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by insertish** [comment]
Hi, you should be able to email security@revolt.chat.
I'll go through and add SECURITY.md now though, thanks for pointing it out.

**Comment by b1nslashsh** [comment]
hey,@insertish 
just mailed

**Comment by b1nslashsh** [comment]
@insertish I think we can close it now

Thanks

**Comment by insertish** [comment]
Yep.
