### ISSUE TITLE
Typing @ in the information text box opens a user list

### ISSUE THREAD

**Issue by That-Thing** [revoltchat/revite#249]
When you type an "@" in the information text box, a list with people from servers I'm in pops out. Not sure if this is intentional or not, but it gets in the way and seems largely unnecessary.  
![image](https://user-images.githubusercontent.com/41160238/133480184-16fa5485-7168-4322-aafe-d9b9c88664b2.png)

**Comment by brecert** [comment]
This is intentional so that you can mention users.

Perhaps it could be made to only pop out after another one or two characters is added.
