### ISSUE TITLE
Using context action "Save Image" on messages with multiple images always downloads the first one

### ISSUE THREAD

**Issue by Andre601** [revoltchat/revite#250]
When a message has multiple images and you use the "Save Image" context action (Right-click image -> "Save Image") on any of the images will you always download the first one of the message, even if you right-clicked a different image, to begin with.

**Comment by rMazeiks** [comment]
I cannot currently reproduce this – the correct image is always downloaded. Perhaps this has already been fixed?

**Comment by insertish** [comment]
This was fixed.
