### ISSUE TITLE
Huge lag/FPS drop during Cycle Collection(and DOM Event?)

### ISSUE THREAD

**Issue by atirut-w** [revoltchat/revite#255]
I am not a web developer so I didn't look too deeply into this, but Firefox performance tab shows that sometimes a DOM Event or a Cycle Collection can take up long amount of time and halting the whole page during that time. Cycle Collection stutters seem to be more frequent and can take more than 2.5 seconds to finish.

![Screenshot from 2021-09-17 12-03-32](https://user-images.githubusercontent.com/25323231/133727967-f390cd37-de0c-4269-979b-461849392d47.png)
![Screenshot from 2021-09-17 12-11-38](https://user-images.githubusercontent.com/25323231/133728060-04aa9674-8321-469a-a931-96262eafccc6.png)

**Comment by bdbch** [comment]
When does this occur or where did you test this? I could take a look into this.

**Comment by atirut-w** [comment]
This seem to happen at random but I'll reply with updates if I find anything else related to this issue.

**Comment by atirut-w** [comment]
On a side note, I suspect this to be from using a lot of `new` variables because it would seem that these kind of variables are garbage-collected. This seem to coincide with Cycle Collection being slow.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
