### ISSUE TITLE
Using Japanese (and probably chinese/korean) leaves typed messages after pressing Enter key

### ISSUE THREAD

**Issue by Steve-0628** [revoltchat/revite#261]
Most Japanese IMEs use the enter key to confirm what the user typed. I think it was same on Chinese and Korean IMEs. 
Revolt app sent the message on enter key even when the key press was intended to confirm inputs. It will prevent most inputs to be done on message textarea. The video below pressed enter key twice finishing input (in this case, "テスト入力")

https://user-images.githubusercontent.com/49326405/133881981-b012c921-517b-4cc4-878a-a8593326ad40.mov

.

**Comment by brecert** [comment]
This will be fixed by #257
