### ISSUE TITLE
Setting language to Arabic flips the entire user interface

### ISSUE THREAD

**Issue by ehea617** [revoltchat/revite#264]
### Summary
Setting the language of Revolt to Arabic flips much of the user interface horizontally. This affects both the web app and desktop app.

### Steps to Reproduce
1. Go to Client Settings and click Language.
2. Set the language to Arabic (2nd option down in the list).
3. The entire UI of Revolt will flip horizontally.

### Screenshots
![image](https://user-images.githubusercontent.com/12926544/133906271-bcaa342d-c699-4b9b-8ad4-e3207330ea17.png)
![image](https://user-images.githubusercontent.com/12926544/133906280-e8a987ff-07a3-4ff7-8888-b7ab6ba15e22.png)

**Comment by brecert** [comment]
I believe this may be intended behavior, due to Arabic being read right to left and the designer intentionally using [css logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) when making the ui

**Comment by insertish** [comment]
This was an intended design decision by nizune, if you believe this should work differently then state your case I guess.
