### ISSUE TITLE
Profile picture appears as black-and-white when editing server identity

### ISSUE THREAD

**Issue by steejo29** [revoltchat/revite#270]
When editing the server-specific identity using the 'Edit identity' feature, the profile picture appears as black and white (or what appears to be significantly de-saturated).

I'm unsure whether or not this is the intended effect.

![image](https://user-images.githubusercontent.com/13812987/133941873-6646a13b-1f6b-4e23-a5a9-4076cb1d3821.png)

**Comment by brecert** [comment]
If your server identity avatar is unset, your global avatar will be shown desaturated to show it hasn't been set yet.

**Comment by steejo29** [comment]
> If your server identity avatar is unset, your global avatar will be shown desaturated to show it hasn't been set yet.

Ah this make sense then :) Though a tooltip or similar would be helpful. Will just close this out.
