### ISSUE TITLE
Censor the entire email

### ISSUE THREAD

**Issue by Micadurp** [revoltchat/revite#274]
Very nice to have it censored to begin with but I believe the whole thing should be censored and not just the first part.

Reason:
If you aren't a part of the big email providers its identifying information and even worse if you have a custom domain for your email.

![email](https://user-images.githubusercontent.com/10599477/133997754-65b366ae-ba79-45ed-80b5-f6a3379aee75.png)

**Comment by Rexogamer** [comment]
I would like to claim this issue
