### ISSUE TITLE
Unchanging Themes

### ISSUE THREAD

**Issue by Jeosty** [revoltchat/revite#276]
## Theme not changing in theme shop if out with default appearance settings.
> Step by step
> Go to settings > appearance > change main color (accent) > go to theme shop or top appearance settings > try select a theme
* Unchanging Themes

**Comment by ActuallyTheSun** [comment]
Temporary fix (or may be intended idk)
Reset theme overrides by going under Appearence -> Theme overrides -> "Reset overrides" (button on left side)
Then it works

**Comment by Jeosty** [comment]
I know that but Devs should fix in the next update.

**Comment by brecert** [comment]
This is the intended behavior, perhaps there should be a warning or notice when you have overrides and are setting a theme.

**Comment by LillieCode** [comment]
> This is the intended behavior, perhaps there should be a warning or notice when you have overrides and are setting a theme.

I agree with this, there should be a way to make users aware of the theme overrides disabling changing theming.
Idea is to have it a text "Theme override is enabled, you can't change themes" and disabling the components to not confuse users.

**Comment by insertish** [comment]
Expect a fix in #137.
