### ISSUE TITLE
Show unread DMs under home button.

### ISSUE THREAD

**Issue by amywastaken** [revoltchat/revite#289]
Inspired by Discord, it should be added. this would be an enhancement to revolt. DMs should look like this (sender's profile image with a notification badge)
![aaaaaaa3](https://user-images.githubusercontent.com/80048740/134390466-41757c8f-eef0-4aaa-8a41-5a639f0afa02.PNG)
while friend request pings should look like this (your profile with a notification badge)
![333333aaaaaaa](https://user-images.githubusercontent.com/80048740/134390561-872b262f-c3d4-45ae-9511-4fc85312b1cd.PNG)

**Comment by Rexogamer** [comment]
Apologies for the delayed response, but this has now been added in 56ab2a291701ddb64641180f9694f13e57d50c71 🎉
