### ISSUE TITLE
Visual issue when opening channels

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revite#299]
https://not-an-iplogger.com/SO79iSHU.gif

**Comment by Nikegamerjjjj** [comment]
Framework's not so fast.

**Comment by insertish** [comment]
Note for quick fix: Apply zero opacity in useLayoutEffect, wait until first scroll event after which we can make it appear again.

Note for proper fix: Would need to hook into the loading mechanism to synchronously render and scroll, but that could hang the page.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
