### ISSUE TITLE
Channel Description + Markdown

### ISSUE THREAD

**Issue by shiiiina** [revoltchat/revite#306]
![image](https://user-images.githubusercontent.com/57958653/134786238-eb3a2bcb-f6b9-43e6-a0d2-ac8018882115.png)

When mentioning a channel in markdown (idk the technical name for the fancy text colour thing) in channel description it just shows the []() for a link

![image](https://user-images.githubusercontent.com/57958653/134786270-8a7976b1-e8aa-40c5-82e0-2460a2bf839d.png)

**Comment by insertish** [comment]
This is not Markdown, this is KaTeX / LaTeX, it's a mathematical typesetting library.
You will not be able to embed any sort of links with it.
