### ISSUE TITLE
AUP checkbox when creating server.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#31]
Force users to agree to the Acceptable Usage Policy when creating a server.

**Comment by kuhnchris** [comment]
Should the AUP be a flag on the user in the database, or should we prompt for AUP whenever the User creates a server?
Also I assume it's the same AUP as linked on the "My Bots" page? https://revolt.chat/aup

**Comment by Rexogamer** [comment]
We decided internally to simply add a notice to the create server modal notifying the user of the AUP. And yes, this is the same AUP

(Also note that I've already pushed a branch to fix this, so don't worry :3)

**Comment by kuhnchris** [comment]
OK, no worries, I was just checking out if there were more open "easy" tasks from me to snatch. ;-)
