### ISSUE TITLE
The Language flags are missing or not loading

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revite#310]
https://not-an-iplogger.com/DrAepBSb.gif

1614d7a (master)
Nightly 1.0.0-vite
Native: 1.0.0
API: 0.5.3-alpha.5
revolt.js: 5.1.0-alpha.0

**Comment by insertish** [comment]
Appears to be an issue with Noto Emoji.

**Comment by insertish** [comment]
Yes, Noto Emoji don't have country flags so I'll need to update the assets to include a fallback.

**Comment by insertish** [comment]
This is being fixed in new client with genemoji.
