### ISSUE TITLE
Discord status bug

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revite#311]
1st: It's showing that im playing a game "[Re-Volt](https://en.wikipedia.org/wiki/Re-Volt)
GIF: https://not-an-iplogger.com/A18KKto1.gif

2nd:  You can't disable the Discord Status, I reloaded Revolt after unchecking the Discord Status but still the same

1614d7a (master)
Nightly 1.0.0-vite
Native: 1.0.0
API: 0.5.3-alpha.5
revolt.js: 5.1.0-alpha.0

**Comment by Nikegamerjjjj** [comment]
@insertish It is a bug, causes on me too.

**Comment by insertish** [comment]
This is just Discord detecting Revolt as something else, nothing I can do about it.

**Comment by Nikegamerjjjj** [comment]
> This is just Discord detecting Revolt as something else, nothing I can do about it.

okay
