### ISSUE TITLE
No content on saved notes / DM members sidebar.

### ISSUE THREAD

**Issue by Danixd12** [revoltchat/revite#313]
You can swipe to the right when you're talking with someone in PM, and you will see an empty member list
![image0](https://user-images.githubusercontent.com/41576632/134930260-8bb5d143-6ff9-45f4-8325-9b5f296343a1.png)

**Comment by Nikegamerjjjj** [comment]
@insertish We got a problem. You hadn't added member list to regular user chats, that includes Save Notes chat too.

**Comment by Evilhotdog** [comment]
@insertish what kind of action would be needed on saved notes if there is no other user?

**Comment by insertish** [comment]
Message search
Also if pins are added they'll probably be available in all channels

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.

**Comment by insertish** [comment]
No, revoltchat/delta was renamed to revoltchat/backend and combined with a few other repositories.
revoltchat/frontend is a new client entirely and is not the same project as this repository.

**Comment by nikeedev** [comment]
> No, revoltchat/delta was renamed to revoltchat/backend and combined with a few other repositories. It's separate.
> And revoltchat/frontend is a new client entirely and is not the same project as this repository.

Nice, but why do you move issues from here to the frontend repo?
