### ISSUE TITLE
UX for "User Joined" system message is confusing

### ISSUE THREAD

**Issue by nchristopher** [revoltchat/revite#316]
The UX for this (see below image) system message for a user joining is a bit confusing. This is a bit of a nitpick, but was noticeable to me when using Revolt for the first time.

![](https://i.imgur.com/uzLU1RO.png)

- The arrow icon to the left of the message gives feedback despite not doing anything when clicked. The cursor changes on hover.
- ~~The joined user's username **is** clickable, but it gives no feedback. The cursor does not change on hover, and the username isn't different from the rest of the text - maybe it should be in bold?~~ Fixed in 21cd3f45586d9dc62c7327d88b04801a3abf541f.

**Comment by Rexogamer** [comment]
The second issue has now been fixed:
![the usernames in user related system messages now use the pointer style cursor and are underlined on hover](https://autumn.revolt.chat/attachments/5aD4Y3rKSagptbltarW3oQi7p6Fc329LkQfhN3jnIz/image.png)
