### ISSUE TITLE
unable to "enable push notifcations" on linux .deb version of the client

### ISSUE THREAD

**Issue by MyCaffeine** [revoltchat/revite#317]
i currently have all other boxes ticked in the notifications tab under client settings but i am unable to tick the   "enable push notifcations" im using pop os 21.0.4 i am using the .deb package running nightly build 1.0.0 - vite 

![image](https://user-images.githubusercontent.com/74573353/135157014-e2a5b038-0d04-4e2a-b840-6c9a79e3e85c.png)

**Comment by insertish** [comment]
Expected behavior, Electron does not provide Web Push service.
