### ISSUE TITLE
Doesn’t switch tabs

### ISSUE THREAD

**Issue by SlenPlayz** [revoltchat/revite#321]
On ios 14.5 when you goto the accounts tab you can't switch back to the chat tab 

https://user-images.githubusercontent.com/67079195/135745527-75d32571-0759-4efa-a914-e72ab422436c.MOV

**Comment by nikeedev** [comment]
> On ios 14.5 when you goto the accounts tab you can't switch back to the chat tab https://user-images.githubusercontent.com/67079195/135745527-75d32571-0759-4efa-a914-e72ab422436c.MOV

Really i dont know why, but not like pc, mobile doesnt have ESC button, making it hard to exit if you swipe. If you only use website, you can use undo button.

**Comment by SlenPlayz** [comment]
> > On ios 14.5 when you goto the accounts tab you can't switch back to the chat tab https://user-images.githubusercontent.com/67079195/135745527-75d32571-0759-4efa-a914-e72ab422436c.MOV
> 
> 
> 
> Really i dont know why, but not like pc, mobile doesnt have ESC button, making it hard to exit if you swipe. If you only use website, you can use undo button.
> 
> 

I'm not swiping i'm literally just clicking it

**Comment by nikeedev** [comment]
I meant that swiping or pressing close button(if you find one) won’t work

**Comment by SlenPlayz** [comment]
The issue got worse the entire settings panel ain't working

**Comment by nikeedev** [comment]
> The issue got worse the entire settings panel stops working when you try to switch back to chats and clicking settings again does nothing

Ehhhhh…restart device?

**Comment by SlenPlayz** [comment]
> > The issue got worse the entire settings panel stops working when you try to switch back to chats and clicking settings again does nothing
> 
> 
> 
> Ehhhhh…restart device?

didn't work

**Comment by insertish** [comment]
This was fixed at some point.

**Comment by nikeedev** [comment]
> This was fixed at some point.

"Magically!"

**Comment by nikeedev** [comment]
> I just don't want to dredge through hundreds of commits to find the exact one.

Yeah, i understand what you mean.
Btw, Going great at uni?
