### ISSUE TITLE
code blocks do not have (enough) padding on the right

### ISSUE THREAD

**Issue by the456gamer** [revoltchat/revite#322]
code blocks do not have (enough) padding on the right

See attached video

https://user-images.githubusercontent.com/42748092/135883617-88132e1c-3025-45b9-9c69-c88fb999e624.mp4

Makes it harder to see the edge of the code

**Comment by Nikegamerjjjj** [comment]
> code blocks do not have (enough) padding on the right
> 
> See attached video
> 
> https://user-images.githubusercontent.com/42748092/135883617-88132e1c-3025-45b9-9c69-c88fb999e624.mp4
> 
> Makes it harder to see the edge of the code

Remember that it is Web client and are mainly made for desktop use. Could be problem that the code you got is long? because thats normal.

**Comment by the456gamer** [comment]
> Remember that it is Web client and are mainly made for desktop use

Is there a seperate issue tracker for mobile issues? If so, sorry

I just believed that the code block deserved padding on the right, like on the left

**Comment by Nikegamerjjjj** [comment]
> > Remember that it is Web client and are mainly made for desktop use
> 
> Is there a seperate issue tracker for mobile issues? If so, sorry
> 
> I just believed that the code block deserved padding on the right, like on the left

1. No, there isn’t any other tracker for mobile as web client is for web not for mobile only. Insrt are working on making android app for revolt but only android, as Apple developer account are too expensive. 
2. Changing padding may cause change on design even on desktop which I think is not a great idea.
3. 


Any more questions? 

If not: 
Have good day further!

**Comment by Nikegamerjjjj** [comment]
Hope you know that insrt is going at uni, so money isn’t easy in that time. That’s waste of money on paying again and again, when you have already Uni to pay to.

**Comment by insertish** [comment]
Can't seem to reproduce?

![image](https://user-images.githubusercontent.com/38285861/136697249-8684e421-7150-4142-a93c-fd3c07bccb2c.png)

What version of Firefox are you running?
