### ISSUE TITLE
Sent time overlap

### ISSUE THREAD

**Issue by the456gamer** [revoltchat/revite#324]
# With edited

![here with edited](https://user-images.githubusercontent.com/42748092/135892584-ffe68bb6-1cc0-4bb3-827a-5859fd986761.png)

# offset in an annoying way on join msg

![image](https://user-images.githubusercontent.com/42748092/135892873-3a7bec66-ca6d-4d7d-9df9-60d1685e5236.png)

**Comment by insertish** [comment]
Closing in favour of https://github.com/revoltchat/revite/issues/333.
