### ISSUE TITLE
Re-build Message components.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#333]
The message components are a tad bit messy, need to re-write them to be more consistent and easily embedded, ideally it should have minimum required data and can be taken out of the project to be used elsewhere (e.g. landing page or other util).

Linked to #316, #324

**Comment by kcseb** [comment]
Images that are marked as spoilers (`SPOILER_name.ext`) will resolve as an overcast, creeping mess. At least the spoiler works! 
![img](https://i.imgur.com/vNBGp9u.png)

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
