### ISSUE TITLE
Only animate images on hover.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#34]
We may want to add a new setting to control how this works.

**Comment by kuhnchris** [comment]
Is it OK to pull in a separte library for this? https://www.npmjs.com/package/react-freezeframe / freezeframe.js would fit this description.

**Comment by kuhnchris** [comment]
Apparently this is already used in similar fashion with the user avatar - still image generated on content server and served to the user, animated one served on-demand according to infi and insert.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
