### ISSUE TITLE
Color code on bot edit page

### ISSUE THREAD

**Issue by luckspt** [revoltchat/revite#340]
Color code is correct on desktop web app, but incorrect when using mobile on the /settings/bots page.
Most importantly the delete button should be danger instead of blue, but the save button is also different on those platforms.

[Mobile Screenshot](https://autumn.revolt.chat/attachments/JrxH6NSyFdvlrHrY1uFplxjsW2ay_XPM8NIeU7a2dr/Screenshot_20211015-010744_Chrome.png)
[Desktop Screenshot](https://autumn.revolt.chat/attachments/NC20BL8uTivYHyh7UnrjNOk2sbj42r_kijl1rVzGMn/image.png)

**Comment by ryanalexander** [comment]
![image](https://user-images.githubusercontent.com/38785445/148308673-4d1d84f0-00d5-4d23-a613-dd88cf86b85a.png)
This issues appears to be patched on ios, checking android now.

**Comment by ryanalexander** [comment]
Issue appears to have been fixed in a previous commit
