### ISSUE TITLE
<Unknown User> joined

### ISSUE THREAD

**Issue by shareghzade** [revoltchat/revite#341]
i joined my bot then i kicked it and now when i open revolt web instead of showing the bot's name it shows:
Unknown User joined
Unknown User was kicked

![Screenshot from 2021-10-17 17-14-59](https://user-images.githubusercontent.com/59317713/137630472-fdd21c86-641b-4acc-8e8e-547de395b3ba.png)

**Comment by Rexogamer** [comment]
This has since been fixed.
