### ISSUE TITLE
Disable the browser right-click context menu.

### ISSUE THREAD

**Issue by BorekSigar** [revoltchat/revite#343]
Right clicking messages will show the Revolt menu but right-clicking anywhere else will show the browser one which is annoying because it's not needed and it looks out of place.

**Comment by Rexogamer** [comment]
Reopening due to 27f6420da2b1d268a866792f67e7405385cfd2fa.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
