### ISSUE TITLE
Voice settings microphone selection empty

### ISSUE THREAD

**Issue by cydactyl** [revoltchat/revite#351]
Client Version: 195a9bd (master)
OS: Manjaro-XFCE Latest
Headset: Logitech G930

In both the browser and standalone app the Microphone selection underneath 'Voice Settings' is absent any input device, despite other apps being able to detect it and use it.

![Screenshot from 2021-10-21 22-33-16](https://user-images.githubusercontent.com/1476894/138389244-111e68bd-34f8-46a6-bc03-fce8ffc76949.png)

**Comment by rflrkn** [comment]
I'm experiencing the same on Arch Linux with KDE using Firefox.

The bug is also there on my iPhone with the latest stable version of iOS.

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
