### ISSUE TITLE
add setting to disable the nsfw channel prompt

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revite#366]
Several users and issues have mentioned the fact that every time you open an NSFW channel, you have to go through the age gate. This is an intended feature to prevent misclicks, but it clearly causes frustration for users. I propose a new setting, "Show age gate for NSFW channels" that, when disabled, will suppress this age gate. This setting will, by default, be enabled and the content string should contain something like `By disabling this feature, you confirm that you are 18 years or older.`

An alternative idea is to add a "never show this again" option on the gate itself, but I could see cases where someone might want the gate in some circumstances and not want it in others.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
