### ISSUE TITLE
Opening long link

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revite#372]
Popup when opening sketchy links need some improvements, this is what happen when opening a long link

Image: https://the-anime-god.is-inside.me/FujLUdLx.png

Suggestion: Maybe make it link when you open or delete like in discord? https://the-anime-god.is-inside.me/zhjW7YAH.png

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
