### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by CapybaraPin** [revoltchat/revite#376]
Hello,

I noticed a translation bug in French on your application: 

In the role management the last option which is currently "Masquerade" in French is rather "Mascarade".

Moreover the description of this permission which is currently "Allows users to change their name and avatar per-message." is not translated, in French it would give "Permet aux utilisateurs de changer leur nom et leur avatar par message."

Well, I hope to have helped you in your great project. 
Have a nice day.

**Comment by Rexogamer** [comment]
If a string has been mistranslated, you can fix it [here](https://weblate.insrt.uk). If a string is untranslated and not on Weblate, please report it under #99. Thanks!
