### ISSUE TITLE
Add buttons to invite to channel / go to channel settings on hover.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#38]
Need to check for `InviteOthers` permission and `ManageChannel` permission.

Example from Discord:
![image](https://user-images.githubusercontent.com/38285861/128557934-0e1f7cb7-5e16-4ffe-987d-4f2f07f5bb8e.png)

We should also move the "alert" circle to avoid issues.

**Comment by LillieCode** [comment]
Will work on this later today, unless someone else has already started.

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.
