### ISSUE TITLE
New messages marker appears on server icon despite no channels in channel list being highlighted

### ISSUE THREAD

**Issue by PencilVoid** [revoltchat/revite#385]
![image](https://user-images.githubusercontent.com/83508866/141159128-4cde5497-066d-4288-9b66-053adcbb4d2e.png)
See attached image. Usually when there are channels with with unread messages a dot appears to the right of the channel name. Right-clicking the server icon and selecting "Mark as read" makes the marker disappear until there is an unread message in the server.

**Comment by insertish** [comment]
This was fixed.
