### ISSUE TITLE
Make reply mention toggle's status more visible

### ISSUE THREAD

**Issue by Cosmiiko** [revoltchat/revite#386]
@insertish [Link to Revolt Lounge message where you requested this issue to be opened](https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01F7ZSBSFHCAAJQ92ZGTY67HMN/01FM4HG8PF19VTM909TEHW3K45)

The proposed fix was to make the toggle brighter when on (and/or darker when off).

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
