### ISSUE TITLE
Reply to self

### ISSUE THREAD

**Issue by ChildishGiant** [revoltchat/revite#387]
It's currently not possible to reply to a message you sent. I'd like this so I can refer to a previous message.

**Comment by Rexogamer** [comment]
I'm a little confused - it is? Right-click the message and select `Reply`.
![image](https://user-images.githubusercontent.com/42586271/141186946-88586bfb-8996-44ea-846c-d1db60202b17.png)

**Comment by ChildishGiant** [comment]
Hmm I wasn't able to when I tried before but now seem to get the option. Maybe I was doing it wrong ...
