### ISSUE TITLE
Show users in calls when not selected

### ISSUE THREAD

**Issue by ChildishGiant** [revoltchat/revite#388]
This call has two users in but there's no way to know without clicking into it
![image](https://user-images.githubusercontent.com/13716824/141184589-c97ba925-6833-474a-b67b-1995b43db593.png)

Discord does this like so:
![image](https://user-images.githubusercontent.com/13716824/141184788-679258fe-e94f-4152-acc8-86d54b092a2a.png)
![image](https://user-images.githubusercontent.com/13716824/141184878-71d10cdf-699f-401a-8a10-4929ff25ec5a.png)

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
