### ISSUE TITLE
Suggestion for the channel categories' color

### ISSUE THREAD

**Issue by viralbox** [revoltchat/revite#395]
It would be nice to have the channel categories color be darker, like a darker gray. Or atleast a way to customize it, because when the channels are unread they blend in with the categories.
(Sorry for the really big screenshot, I took this screenshot on my phone.)
![SmartSelect_20211112-222824_Firefox](https://user-images.githubusercontent.com/92414591/141524596-fa6b0c39-00f8-4c86-9cde-14d6cf769d72.jpg)

**Comment by insertish** [comment]
I guess I could keep it the same colour as an unread channel?
I could then make the disabled state either darker or just keep it the same.

**Comment by viralbox** [comment]
> I guess I could keep it the same colour as an unread channel? I could then make the disabled state either darker or just keep it the same.

Yeah sure. It would also be nice to be able to customize it, but it's fine if you are unable or don't want to do that. Someone could just fork it and add that functionality anyway.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
