### ISSUE TITLE
Accessibility Settings

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#40]
We should implement accessibility options at some point.

- [ ] Disable animations
- [ ] Disable transitions
- [ ] Disable icon animations
- [ ] Bold text everywhere
- [ ] High contrast theme
- [ ] Zoom options

**Comment by nchristopher** [comment]
Not sure if this is strictly accessibility, but it'd be nice to have the option to disable channel icons and always show a `#`.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
