### ISSUE TITLE
Can’t go directly from setting to home on IOS

### ISSUE THREAD

**Issue by WhiteEgretOrchids** [revoltchat/revite#402]
I’m using an iPhone (XR) and I just made an account. I went into settings so I could give myself an icon and stuff like that but when I tried to click on the chat icon at the bottom of the screen, it would just flash on the screen for a second and stay in settings. Reloading the page doesn’t get out of it. You can get out of it by clicking the friends icon or removing settings from the url, however I cannot go directly from settings to the home menu.

**Comment by nikeedev** [comment]
> I’m using an iPhone (XR) and I just made an account. I went into settings so I could give myself an icon and stuff like that but when I tried to click on the chat icon at the bottom of the screen, it would just flash on the screen for a second and stay in settings. Reloading the page doesn’t get out of it. You can get out of it by clicking the friends icon or removing settings from the url, however I cannot go directly from settings to the home menu.

You could also click on the undo button, so you will be redirected to the url that doesnt include "/settings/"

**Comment by insertish** [comment]
This was fixed recently, missed this issue since it was marked as iOS specific.
