### ISSUE TITLE
I can't update my revolt desktop app

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revite#404]
I don't know if I posted it in the right issue but I keep reloading my Revolt but still in `8664cda (master)`

```
8664cda (master)
Nightly 0.5.3-1
Native: 1.0.0
API: 0.5.3-alpha.8
revolt.js: 5.1.0-alpha.7
```

**Comment by Rexogamer** [comment]
Are there any errors in the dev console?

**Comment by aeristhy** [comment]
@Rexogamer there are none https://the-anime-god.is-inside.me/nnIH8Bzn.png (the badge error has been fixed in the recent update)

**Comment by aeristhy** [comment]
@insertish any way to fix this issue?

**Comment by aeristhy** [comment]
Update: I reinstalled Revolt app and somehow fixed it. I will be closing this issue now
