### ISSUE TITLE
Selecting different server while channel view is collapsed causes incorrect behaviour

### ISSUE THREAD

**Issue by TaiAurori** [revoltchat/revite#408]
When entering some servers with a session that the user has not selected a channel in the server with previously, with the channel view collapsed, the main view reads "This server has no channels, or you don't have access to any." even in servers with channels in them and the channel view cannot be reopened.
The latter is because the "No channel" placeholder's `Hash` isn't clickable like the default one, which should preferably be changed.

**Comment by insertish** [comment]
This was fixed with c26ef4c2b243f3a195d812d4593094f82a54cf83
