### ISSUE TITLE
(Feature Request) Add discord-esqe ctrl+k navigation for non-mouse users

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [revoltchat/revite#409]
(how do i add tags to github issues)
Please add ctrl+k navigation, similar to discord, so that non-mouse and keyboard-centric users can easily navigate.
Tab just ain't cutting it.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
