### ISSUE TITLE
Move away from hCaptcha 

### ISSUE THREAD

**Issue by jgg2O** [revoltchat/revite#412]
Just a suggestion to move away from hCaptcha as it's not privacy respecting, plus there is many alternatives out there such as the open source FriendlyCaptcha https://friendlycaptcha.com/

**Comment by insertish** [comment]
Worth noting Friendly Captcha is paid, but we do have a similar concept in the works.

**Comment by insertish** [comment]
Opened issue in authentication library here: https://github.com/insertish/rauth/issues/30
