### ISSUE TITLE
Embed message links.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#418]
Sending a link such as https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01FDAHKCQ96CGMGC8YYC74F75W/01FN9A2YYXVMJQVD9CBJG2X1VZ should cause it to fetch and display the message, regardless of whether said message is in the same channel or server.

**Comment by Rexogamer** [comment]
I could see some privacy/perm issues here - say if someone leaked the message link of a very private and personal rant. IDs can also be automatically generated/found with enough effort, so unlike message content/screenshots this could potentially be brute-forceable. If they were limited to being within the same server (applying perms correctly) then I could see this working fine, but still

**Comment by insertish** [comment]
The idea is that it fetches it on the client side, so all your relevant permissions apply.

**Comment by Rexogamer** [comment]
Ahhhh - fair enough, sounds great to me

**Comment by TaiAurori** [comment]
Design mockups?

**Comment by nerrixDE** [comment]
Important: Ability to supress the embed with `<link>`

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
