### ISSUE TITLE
Clicking on an invite while logged out and then logging in does not accept invite

### ISSUE THREAD

**Issue by limethyst** [revoltchat/revite#419]
When you click on an invite link to a Revolt server while you aren't logged in to Revolt, you are prompted to log in to Revolt to join the server. After logging in by pressing the button ("Login to Revolt"), you are sent to the home page and not added to the server (requiring you to go back and click on the invite link again).

The invite prompt should probably be displayed again after logging in.

**Comment by insertish** [comment]
This was fixed in 1b6275d1b52aff274750e346a4d4cf661546866d.
