### ISSUE TITLE
Add confirmation modal when logging out of all other sessions.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#42]
Example from Twitter:
![image](https://user-images.githubusercontent.com/38285861/128558726-628fdc40-0ae0-4c73-98a2-8b557b7369fc.png)

**Comment by Rexogamer** [comment]
I would like to claim (and once my other PRs are dealt with, work on) this

**Comment by 3nt3** [comment]
*did* you work on this? otherwise I would like to try to do this

**Comment by Rexogamer** [comment]
Not sure why this wasn't auto-closed, but this was added in ac0c100846e70618f76f6de89e7df37ca2c3403a :tada:
