### ISSUE TITLE
Functional issue : Search User only starts upon pressing enter

### ISSUE THREAD

**Issue by zDEFz** [revoltchat/revite#426]
Enter your user ID, click on latest. Nothing happens. Press Enter, the search is being done.

**Comment by Rexogamer** [comment]
Hmmm... it seems as though clicking on Oldest then clicking back to Latest performs the search? Not sure if this is a bug per se, but possibly something to be improved upon.

https://user-images.githubusercontent.com/42586271/147107716-08a638d6-6820-4599-8ada-de72774e53f4.mp4

**Comment by zDEFz** [comment]
https://user-images.githubusercontent.com/24463722/147165132-64588e61-642c-4846-a1fe-74648e5f4411.mp4

Yea exactly. But cant get results when I press on latest first.

**Comment by insertish** [comment]
Note: Related piece of code either uses `useEffect` to listen to changes or just prevents anything from happening if no state changes.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
