### ISSUE TITLE
Bug report: Search doesn't show the most recent mentions

### ISSUE THREAD

**Issue by zDEFz** [revoltchat/revite#428]
Steps done: Changing profile picture only for this server, grabbing id from user settings, entering the id in search, pressing enter.
Only the results from prior to the profile picture change just for one unique server come up.
But not the results associated to after I did this change.

**Comment by Rexogamer** [comment]
Hmmm... can't seem to reproduce locally - would you be able to provide a screen recording of some kind?

**Comment by Rexogamer** [comment]
Issue author has confirmed that this is no longer an issue:
![image](https://user-images.githubusercontent.com/42586271/147165606-3dde3d4a-b25a-4ce3-b471-8b85e91bf74b.png)
