### ISSUE TITLE
Feature request: Restore window state, including cursor and scroll state

### ISSUE THREAD

**Issue by zDEFz** [revoltchat/revite#429]
Story: When user closes revolt and for instance wrote a question, but then closes the browser to later see what answer was sent, there should be an option to keep the current scrolling position.
So, the scrolling position for when the user closed the browser cannot be the most recent one, but the position of when the user was last online and sent a message.

**Comment by insertish** [comment]
This is probably out of scope, although partially solved by fee56d8f546460d67f9424be808cc40161ea31e0 which lets you optionally jump back to last position.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
