### ISSUE TITLE
Error open chat in settings

### ISSUE THREAD

**Issue by codehyna** [revoltchat/revite#435]
Hello, the error is that when you enter the direct link https://app.revolt.chat/settings, and then you want to return to chat, or press esc to close the menu, it returns to the previous tab outside the app, only It happens when you open the direct link, if you open it settings while in the chat it works fine

https://user-images.githubusercontent.com/95721369/145112747-793686f5-0470-4c0b-9050-2eb451013bb6.mp4

**Comment by Rexogamer** [comment]
Can reproduce on Firefox and Edge, but weirdly this works as intended (i.e. returns to Revolt's home screen) on Safari for iOS

**Comment by insertish** [comment]
This was fixed.
