### ISSUE TITLE
bug: can drag badges (and then upload them by dropping in app)

### ISSUE THREAD

**Issue by doggogqgqgqgqgqgqgqgqgqg** [revoltchat/revite#437]
Clicking the early adopter badge uploads the svg to whatever chat your in.

**Comment by nerrixDE** [comment]
Which platform and Client? Can't reproduce

**Comment by infi** [comment]
Can reproduce when dragging the badge into the sidebar. Also happens with server icons.

![image](https://user-images.githubusercontent.com/45950794/146829802-9d15585d-5fcd-4b2b-a4e7-b359325c6ecd.png)

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
