### ISSUE TITLE
Support for Facecam

### ISSUE THREAD

**Issue by KiritoStorm** [revoltchat/revite#444]
So I would really like to switch from Discord to Revolt, but one thing I really miss on Revolt is a Facecam feature.
I have seen live steaming is in planning, so adding a Facecam feature to would be really cool.

There are a lot of ways to make remote calls today, so I guess there should be a way to maybe implement an open source libary for that.

**Comment by Rexogamer** [comment]
This relies on revoltchat/vortex#5.

**Comment by insertish** [comment]
Closing this so it can be tracked from one issue.

**Comment by KiritoStorm** [comment]
Sorry, I haven't seen that. Great to see that it's plannend. 👍
