### ISSUE TITLE
Handle file limit errors better

### ISSUE THREAD

**Issue by lenrik1589** [revoltchat/revite#446]
Thee shall not be able to stop client's operation upon showing a file too powerful for the client to understand:
![image](https://user-images.githubusercontent.com/48890625/145745103-13d0243d-e538-467b-8692-20bf3a78b655.png)
(`ok` button should not be there, or *ideally* client should not encounter an error upon recieving a fille too big)

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
