### ISSUE TITLE
open rvlt.gg links in-app

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revite#453]
Currently, `rvlt.gg` invites open in the user's browser instead of Revite itself.

**Comment by Rexogamer** [comment]
Turns out this might be a bug/oversight - `rvlt.gg` is listed as an invite link but not as an allowed origin? I'll PR a fix in a bit, but hmmm

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
