### ISSUE TITLE
Attempting to join any server gives "Unauthorized"

### ISSUE THREAD

**Issue by Evilhotdog** [revoltchat/revite#465]
Attempting to join any server, either from links on revolt.social, or the app's testing server, gives an "unauthorized" message. This means that the only servers I can join are ones that I create myself.

**Comment by insertish** [comment]
Fixed in f0c2829c5813cd2750c915f01a6c7a2453d0a393

**Comment by Evilhotdog** [comment]
Thanks. When will this take effect?

**Comment by aeristhy** [comment]
> Thanks. When will this take effect?

update your client

**Comment by Evilhotdog** [comment]
> 

Yeah, that worked, thanks
