### ISSUE TITLE
Issues in server settings(categories tab)

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revite#467]
### I created more than 3 categories and I can't see the other categories or scroll to other categories. The screenshot below explains this
![issue 1](https://user-images.githubusercontent.com/31789752/147421307-3eb78a14-74fd-49cb-b630-c743be807649.png)

![issue 2](https://user-images.githubusercontent.com/31789752/147421309-78831e89-70c0-4e8f-b6f0-6404f6860b85.png)

**Comment by Rexogamer** [comment]
Can't reproduce locally - scrolling sideways works fine for me?

**Comment by aeristhy** [comment]
> Can't reproduce locally - scrolling sideways (both using two fingers on my trackpad and, after clicking on the scroll bar, the arrow keys/dragging the bar) works fine for me? Can you provide a bit more info as to what scroll method you're using?

This need some improvements, I just realize that you can use arrow keys on keyboard to scroll the categories. There are no scroll bar or anything in the desktop client. I did not expect you need to use arrow keys to scroll something sideways

**Comment by Rexogamer** [comment]
There's a scroll bar...?
![image](https://user-images.githubusercontent.com/42586271/147840520-abe3b808-3e3d-40c9-a860-4e9c1d6a47e5.png)

**Comment by aeristhy** [comment]
> There's a scroll bar...? ![image](https://user-images.githubusercontent.com/42586271/147840520-abe3b808-3e3d-40c9-a860-4e9c1d6a47e5.png)

ah it's because of the theme(Nocturnal) I am using. I will open a pr fixing this issue
