### ISSUE TITLE
border-radius does not match on profile preview

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#47]
![image](https://user-images.githubusercontent.com/38285861/128596752-5996777a-d100-4673-90ee-9bf3908e5440.png)

**Comment by ashishcas** [comment]
@insertish  can u assign this issue to me

**Comment by ashishcas** [comment]
@insertish  can u provide me some test credentials to test the changes in local

**Comment by insertish** [comment]
You can make an account through https://revolt.chat/publicbeta

**Comment by ashishcas** [comment]
@insertish  https://github.com/revoltchat/revite/pull/67

**Comment by insertish** [comment]
Closed in #67
