### ISSUE TITLE
Unable to open clipboard on bromite

### ISSUE THREAD

**Issue by Flam3z** [revoltchat/revite#471]
When i reach the sign in page i am unable to hold down onto the email or password space to paste down my information easier.

device: Samsung Galaxy S10
Version: Nightly 0.5.3-1
API: 0.5.3-alpha.11
revolt.js: 5.2.2
[Master](https://github.com/revoltchat/revite/commit/ce3be17b744b2ba91e048e5d5dd1ac6f38917dcc)

**Comment by Rexogamer** [comment]
I'm a little confused - as a non-Bromite/Android user, how does this normally work?

**Comment by Flam3z** [comment]
@Rexogamer you press and hold onto the field where you type an option of using your clipboard would pop up.

**Comment by Rexogamer** [comment]
If possible, would you be able to provide a screen recording or something similar?

**Comment by Flam3z** [comment]
Sure, i'll post one later today.

**Comment by Flam3z** [comment]
@Rexogamer as you can see i attempt to hold down and press for the option of a clipboard which is an issue I have not faced on any other site.

https://user-images.githubusercontent.com/57234536/147720771-c00898e7-2f43-46ca-bb45-4316ade59e2f.mp4

**Comment by Rexogamer** [comment]
I see - apologies for the hassle, but would you be able to show this working as expected on another site or something?

**Comment by Flam3z** [comment]
Uploading Screen_Recording_20211230-134110_Bromite.mp4…

**Comment by Flam3z** [comment]
https://user-images.githubusercontent.com/57234536/147779574-45f76313-18eb-48fc-9423-12398b09dd6f.mp4

**Comment by insertish** [comment]
I think this may be related to https://github.com/revoltchat/revite/issues/406, may need to just reverse the original commit

**Comment by locness3** [comment]
> I think this may be related to #406

So a solution would be to re-enable the browser context menu on inputs?

**Comment by Rexogamer** [comment]
Fixed in 27f6420da2b1d268a866792f67e7405385cfd2fa.
