### ISSUE TITLE
Revolt - server channel changes issue

### ISSUE THREAD

**Issue by olfenolek** [revoltchat/revite#474]
Hey there,
I'm making a server for me and some friends and there is that really strange bug that when I'm changing as example the channel name or description and click on the save button below it just doesn't save it. I tried it severeal time but it sometimes rarely works and other times not. Hope you guys can fix this, thanks tho for the amazing program!
Have a nice day,
Olsen

https://user-images.githubusercontent.com/85935286/147661040-c89e408a-ebaa-4dab-a156-184815ef30ef.mp4

**Comment by Rexogamer** [comment]
Can you check the dev console for any errors (CTRL-Shift-I)?

**Comment by insertish** [comment]
Can confirm this is happening on occasion.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
