### ISSUE TITLE
[WINDOWS 11]: Revolt Desktop starts up on start, when the setting are off.

### ISSUE THREAD

**Issue by nikeedev** [revoltchat/revite#476]
*So i just a quick info before i tell the issue: I have upgraded to Windows 11, so this could be why this error maybe happened.*

**Also it is pictures here, so if you are watching issue on Discord**

The issue:

I had Windows 10, and i had "Start up with computer" on, but after upgrading to Windows 11, i turned this feature off:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/69197950/147755016-227fec23-89a2-49af-b825-0f57ed59292d.png">

but after restarting Revolt kept opening after restart.

The only way to deactivate, was to go to Task Manager( taskmgr command ), like here: 

<img width="343" alt="image" src="https://user-images.githubusercontent.com/69197950/147755276-2edf1c6a-4b60-44b6-b67f-e02cba77c03f.png">

Right click the app, and click deactivate.

**Comment by Rexogamer** [comment]
Can't seem to reproduce - it enables/disables as expected on my machine:

https://user-images.githubusercontent.com/42586271/147761467-15ab8713-695b-4919-bcbf-54e0fc8763c2.mp4

**Comment by nikeedev** [comment]
**@Rexogamer, Remember that i had "Start with computer" turned on Windows 10.**


Wait. After upgrading it moved all apps and   functions from win10 to win11.


Maybe after the move it moved all startup apps from win 10 and some of them maybe didnt turn off or maybe a error occurred just then. I will try tomorrow to turn it back on restart and see if it will turn off..

**Comment by Rexogamer** [comment]
I upgraded to W11 a while back (the first Insider build) and am still in the Dev ring, so as you say it might be an issue related to the upgrade.

**Comment by nikeedev** [comment]
After restart, the function working now!
