### ISSUE TITLE
Internal links should handle other origins such as nightly.

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#48]
Currently clicking a nightly link on stable or vice-versa opens a new tab.

**Comment by janderedev** [comment]
Question - How would this be implemented? I can see how you'd hardcode a list of domains for the official revolt instance at revolt.chat, but that would just break in selfhosted environments that connect to a seperate API backend.

**Comment by insertish** [comment]
I would just hard-code the official instance URLs for now but in a way that I can read it from server configuration later.
