### ISSUE TITLE
Embedded video player jitters / has incorrect sizing.

### ISSUE THREAD

**Issue by oomfiee** [revoltchat/revite#480]
A Weird Bug that breaks the UI (of the video player or the chat UI itself) because of the embedded video player (Android 11, Chrome PWA)

https://user-images.githubusercontent.com/80048740/147960792-de6890e6-7779-405a-b461-30ffe297d054.mp4

https://user-images.githubusercontent.com/80048740/147960891-a15163b3-f685-4bba-b131-eb93771011a9.mp4

**Comment by insertish** [comment]
Fixed in new client.
