### ISSUE TITLE
[Bug Report] Revite ignores VITE_API_URL

### ISSUE THREAD

**Issue by jim3692** [revoltchat/revite#501]
### What happened?

Since [this update on RevoltClient.tsx](https://github.com/revoltchat/revite/commit/f8b8d96d3d34a7e13b0c8f62c09c01f54d247daa#diff-8a8c61dd3b3475e6654257c7f55e6a39965fd1821510cb1dd7163a9c512e6bc1), VITE_API_URL environment variable is ignored, and the app connects to the official API instead of my server.

I see in the commit that `import.meta.env.VITE_API_URL` and other options are no longer passed to Client

### Branch

Production (app.revolt.chat)

### Commit hash

8d1e26d03e7f1cc1ab785ebd966fb1e738d0f13d

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Zomatree** [comment]
https://github.com/revoltchat/revite/blob/8d1e26d03e7f1cc1ab785ebd966fb1e738d0f13d/src/mobx/stores/ServerConfig.ts#L47 its passed here.

**Comment by jim3692** [comment]
https://github.com/revoltchat/revite/blob/8d1e26d03e7f1cc1ab785ebd966fb1e738d0f13d/src/context/revoltjs/RevoltClient.tsx#L53
Maybe this overwrites the config in the state

**Comment by insertish** [comment]
Fixed in fc046936aa6c4e6713291f6f95a470f4710e37b5.
