### ISSUE TITLE
[Bug Report] Switching servers doesn't update members list

### ISSUE THREAD

**Issue by greysdawn** [revoltchat/revite#507]
### What happened?

I currently am in two servers on Revolt: the official testers server, and a private one I've created. Starting up the app in Chrome on Android and navigating to a server, or refreshing from inside of one, seems to load the members bar for that server and *only* that server until you refresh somewhere else, even after switching servers

(Unable to test on desktop currently, will update when able to)

### Branch

Production (app.revolt.chat)

### Commit hash

90a53452e84ea199b8c952673c5de5bd95635630

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Inky1003** [comment]
Also noticed that, on desktop that does not occur.

**Comment by Rexogamer** [comment]
Applying PWA label - seems to only be happening on mobile/the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
