### ISSUE TITLE
[Bug Report] Why a specific video file does not send?

### ISSUE THREAD

**Issue by Inky1003** [revoltchat/revite#510]
### What happened?

I was about to send a bug report with a video, and about to send that video to Revolt, but for no reason It shows that the video is 0 bytes! Downloading is not even possible.

Tried to send other videos, but they send normally.

When asking about Revolt's max file size, I got 50 and 20 mb, but my video was 15mb.

The video I sent was [this one](https://drive.google.com/file/d/1-iqUMwyHaM4lcmx08iGwU4w-yXdBxuMz/view?usp=sharing)

Both a problem on PWA and Desktop.

EDIT: Fixed access permission for the file

### Branch

Production (app.revolt.chat)

### Commit hash

8fcda5a

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
It seems there are none, actually. All I see is this, and all the links related are from servers (i suppose, because they have "invite" on it):

Failed to load resource: the server responded with a status of 404 ()
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by 3nt3** [comment]
You deleted [the file](https://drive.google.com/file/d/1-iqUMwyHaM4lcmx08iGwU4w-yXdBxuMz/view?usp=sharing)

**Comment by Inky1003** [comment]
I'm sorry, I forgot this issue as time passed by, and I think I don't have the video anymore... I think you can close the issue until we found the issue again...
