### ISSUE TITLE
[Feature Request] Convert KateX errors to Tooltips

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revite#512]
### What do you want to see?

Currently, KateX errors use a `<title>` element to share errors. This can be quite ugly depending on the browser. A tooltip containing the error would be a better idea in my opinion.

### Commit hash

4526a696c636151e64747773961a55556b52d61a

### Branch

Nightly (nightly.revolt.chat)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
