### ISSUE TITLE
[Bug Report] Revite soft-crashes when trying to change channel icons without permission

### ISSUE THREAD

**Issue by Inky1003** [revoltchat/revite#513]
### What happened?

I was sending an icon to a channel in my friend's server, and then It show I've no permission, and then I couldn't click anywhere on revolt's app.

A friend who uses a navigator also confirmed this happens there.

![image](https://user-images.githubusercontent.com/13457223/149632573-9236cd70-1da4-4105-be25-935ddcb8a3c7.png)

### Branch

Production (app.revolt.chat)

### Commit hash

79114d7

### Relevant log output

```
Failed to load resource: the server responded with a status of 403 ()
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Just to be clear, is this happening when you try to set a channel icon?

**Comment by Inky1003** [comment]
yes

**Comment by trashtemp** [comment]
Just chiming in - seems like you can enter any server settings of any server through a given link, it shows you can edit the server name, icon, rearrange channels, etc., but in reality nothing gets changed since the user doesn't have permissions, but after exiting the server settings, the client hangs up and requires a restart.

**Comment by Inky1003** [comment]
I mean, my friend confirmed I have "manage channels" permission, but I can't change the icon, so It hangs up and requires a restart after the icon is sent

**Comment by janderedev** [comment]
> Just chiming in - seems like you can enter any server settings of any server through a given link, it shows you can edit the server name, icon, rearrange channels, etc., but in reality nothing gets changed since the user doesn't have permissions, but after exiting the server settings, the client hangs up and requires a restart.

About the first part - I made a PR for that a while ago, but it never got merged. I can try to fix the merge conflicts later

**Comment by Inky1003** [comment]
Also, just to be clear: I had permission to change the icons also.
