### ISSUE TITLE
Opening NSFW channel without dismissing 18+ warning marks channel as read

### ISSUE THREAD

**Issue by TaiAurori** [revoltchat/revite#514]
### What happened?

The channel should still be unread because the user hasn't seen any messages. The channel is clearly read when it is navigated away from, however.

### Branch

Production (app.revolt.chat)

### Commit hash

2bef311

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
