### ISSUE TITLE
[Bug Report] Emoji colon syntax triggered in the middle of strings

### ISSUE THREAD

**Issue by ghost** [revoltchat/revite#515]
### What happened?

From natejgardner:
> Only recommend emojis with colon syntax when not embedded in a string. Typing times in revolt is surprisingly difficult 9:30 can't be typed without it coming out like 9🕧 if it's the last part of the message.

Also suggested to add to let the escape key cancel the emoji colon syntax

### Branch

Production (app.revolt.chat)

### Commit hash

2bef311

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
The auto complete to this day still annoys the shit out of me when in the middle of a string.

Closing due to rewrite, marking as issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
