### ISSUE TITLE
[Bug Report] Can't deny friend requests from suspended users

### ISSUE THREAD

**Issue by Lutitious** [revoltchat/revite#525]
### What happened?

this user is suspended and i cant fucking decline his friend request. fix now or u ugly

https://user-images.githubusercontent.com/25961265/151245233-7eddba48-fc4b-4874-ab95-035afb311db4.mp4

### Branch

Production (app.revolt.chat)

### Commit hash

idfk here
![image](https://user-images.githubusercontent.com/25961265/151244950-f6a12e13-f894-45e9-80f6-3eb4a9570f56.png)

### Relevant log output

```shell
vendor.a06e6009.js:28 PUT https://api.revolt.chat/users/Vladimir/friend 409
(anonymous) @ vendor.a06e6009.js:28
bp @ vendor.a06e6009.js:28
Pb @ vendor.a06e6009.js:28
to.request @ vendor.a06e6009.js:28
(anonymous) @ vendor.a06e6009.js:27
(anonymous) @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
t @ vendor.a06e6009.js:29
req @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
an @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
ov @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
onClick @ RevoltApp.990bc667.js:7
kf @ vendor.a06e6009.js:1
vendor.a06e6009.js:27 Uncaught (in promise) Error: Request failed with status code 409
    at yp (vendor.a06e6009.js:27:14194)
    at ib (vendor.a06e6009.js:27:14318)
    at XMLHttpRequest.d (vendor.a06e6009.js:28:1547)
yp @ vendor.a06e6009.js:27
ib @ vendor.a06e6009.js:27
d @ vendor.a06e6009.js:28
Promise.then (async)
l @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
an @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
ov @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
onClick @ RevoltApp.990bc667.js:7
kf @ vendor.a06e6009.js:1
vendor.a06e6009.js:28 PUT https://api.revolt.chat/users/Vladimir/friend 409
(anonymous) @ vendor.a06e6009.js:28
bp @ vendor.a06e6009.js:28
Pb @ vendor.a06e6009.js:28
to.request @ vendor.a06e6009.js:28
(anonymous) @ vendor.a06e6009.js:27
(anonymous) @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
t @ vendor.a06e6009.js:29
req @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
an @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
ov @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
onClick @ RevoltApp.990bc667.js:7
kf @ vendor.a06e6009.js:1
vendor.a06e6009.js:27 Uncaught (in promise) Error: Request failed with status code 409
    at yp (vendor.a06e6009.js:27:14194)
    at ib (vendor.a06e6009.js:27:14318)
    at XMLHttpRequest.d (vendor.a06e6009.js:28:1547)
yp @ vendor.a06e6009.js:27
ib @ vendor.a06e6009.js:27
d @ vendor.a06e6009.js:28
Promise.then (async)
l @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
an @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
ov @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
onClick @ RevoltApp.990bc667.js:7
kf @ vendor.a06e6009.js:1
vendor.a06e6009.js:28 PUT https://api.revolt.chat/users/Vladimir/friend 409
(anonymous) @ vendor.a06e6009.js:28
bp @ vendor.a06e6009.js:28
Pb @ vendor.a06e6009.js:28
to.request @ vendor.a06e6009.js:28
(anonymous) @ vendor.a06e6009.js:27
(anonymous) @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
t @ vendor.a06e6009.js:29
req @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
(anonymous) @ vendor.a06e6009.js:29
an @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
ov @ vendor.a06e6009.js:29
addFriend @ vendor.a06e6009.js:29
onClick @ RevoltApp.990bc667.js:7
kf @ vendor.a06e6009.js:1
vendor.a06e6009.js:27 Uncaught (in promise) Error: Request failed with status code 409
    at yp (vendor.a06e6009.js:27:14194)
    at ib (vendor.a06e6009.js:27:14318)
    at XMLHttpRequest.d (vendor.a06e6009.js:28:1547)
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by ryanalexander** [comment]
Unable to replicate. Has this possibly been patched already?
POST  https://api.revolt.chat/users/friend
{username: "Skype"}

RESPONSE
{"_id":"01FD5SQXW3WVY5S7T13DZT4BF8","username":"Skype","avatar":{"_id":"ILsMFXjal_CCRd-lQaB6PEv9k4jy_6Ivh1GWR8AYzj","tag":"avatars","filename":"1200px-Skype_logo_(2019–present).svg.png","metadata":{"type":"Image","width":1200,"height":1211},"content_type":"image/png","size":129142},"badges":256,"flags":1,"relationship":"Friend"}

--

Account 'Skype' is my alt which was disabled for testing purposes.
Is anyone else still able to replicate this?

**Comment by ryanalexander** [comment]
> This is about declining incoming friend requests - your request appears to be sending one to the disabled user instead

POST https://api.revolt.chat/users/friend
{username: "Skype"}

RESPONSE
{"_id":"01FD5SQXW3WVY5S7T13DZT4BF8","username":"Skype","avatar":{"_id":"ILsMFXjal_CCRd-lQaB6PEv9k4jy_6Ivh1GWR8AYzj","tag":"avatars","filename":"1200px-Skype_logo_(2019–present).svg.png","metadata":{"type":"Image","width":1200,"height":1211},"content_type":"image/png","size":129142},"badges":256,"flags":1,"relationship":"Outgoing"}

--

DELETE https://api.revolt.chat/users/01FD5SQXW3WVY5S7T13DZT4BF8/friend
{"_id":"01FD5SQXW3WVY5S7T13DZT4BF8","username":"Skype","avatar":{"_id":"ILsMFXjal_CCRd-lQaB6PEv9k4jy_6Ivh1GWR8AYzj","tag":"avatars","filename":"1200px-Skype_logo_(2019–present).svg.png","metadata":{"type":"Image","width":1200,"height":1211},"content_type":"image/png","size":129142},"badges":256,"flags":1,"relationship":"None"}

--

Issue is 100% fixed.
Both ways work as expected with a banned user
@Rexogamer

**Comment by Lutitious** [comment]
Ok cool since its fixed ig ill close the issue feel free to reopen if it turns out to not be fixed.
