### ISSUE TITLE
Caller-List "explodes" when there are too many people

### ISSUE THREAD

**Issue by X4** [revoltchat/revite#533]
### What happened?

Hi

I just experienced the following issue, when joining the lobby and going into a call, with apparently many (muted) users:

![image](https://user-images.githubusercontent.com/84343/152835712-ba66238c-e956-4e64-a212-817f17cf96df.png)

Ideally you can scroll or have a different way of displaying users depending on the amount of users. 

### Branch

Production (app.revolt.chat)

### Commit hash

master

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
This issue was fixed.
