### ISSUE TITLE
[Feature Request] Blocking certain masqueraded usernames 

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [revoltchat/revite#541]
### What do you want to see?

Having the ability to block certain users through bridges.

### Commit hash

3632b6b35187696ccd15c0a28ce76a1451db6c68

### Branch

Nightly (nightly.revolt.chat)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by insertish** [comment]
Not feasible, can also likely hit a lot of false-positives.
