### ISSUE TITLE
[Bug Report] rvlt.gg refused to connect

### ISSUE THREAD

**Issue by RedstoneWizard08** [revoltchat/revite#543]
The frame in which rvlt.gg loads is not working in a self-hosted instance of Revolt. It just shows "Refused to Connect."
This seems to be an issue with `rvlt.gg`'s Content Security Policy. Please fix this.

**Comment by Zomatree** [comment]
This is intentional, you cannot use rvlt.gg from selfhosted instances.

**Comment by RedstoneWizard08** [comment]
@Zomatree is there some alternative, then?

**Comment by Zomatree** [comment]
No.

**Comment by RedstoneWizard08** [comment]
Darn it.
