### ISSUE TITLE
Some French translations

### ISSUE THREAD

**Issue by kaplego** [revoltchat/revite#545]
The following button tooltips are not translated in French :

- Add a server (Sould be "Ajouter un serveur")
- Discover Revolt (Should be "Découvrir Revolt")
- Settings (Should be "Paramètres")

Those three tooltips are on the servers sidebar.

**Comment by kaplego** [comment]
Found new not-translated text : 
"Want to change your username? Head over to your account settings." in the Profile settings
The French translation should be "Vous voulez changer votre nom d'utilisateur ? Rendez-vous dans les paramètres de votre compte."

**Comment by Rexogamer** [comment]
Closing in favour of #99.
