### ISSUE TITLE
[Bug Report] Android Application Does Not Respect Rotation Lock

### ISSUE THREAD

**Issue by kcseb** [revoltchat/revite#548]
### What happened?

On Android, the Revolt app does not respect rotation lock. 

Simply put, if you enable rotation lock, Revolt will still go into landscape mode.

Tested on Android 12, OneUI 4.0, Revolt App Ver. 4

### Branch

Production (app.revolt.chat)

### Commit hash

3632b6b35187696ccd15c0a28ce76a1451db6c68

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by sergiorgb** [comment]
I have this problem too

**Comment by kcseb** [comment]
Turns out this issue doesn't occur on the F-Droid version, so I'd suggest migrating to that version. @sergiorgb

**Comment by sergiorgb** [comment]
F-droid there is none?

**Comment by kcseb** [comment]
See https://fdroid.revolt.chat/repo/

**Comment by insertish** [comment]
Fix currently rolling out to Google Play.
