### ISSUE TITLE
[Feature Request] Enter after opening codeblock shouldn't send message

### ISSUE THREAD

**Issue by anand2312** [revoltchat/revite#552]
### What do you want to see?

Currently, pressing the enter key after opening a codeblock (with triple backticks) immedietely sends the message. It would be more convenient if the enter key took you to a new line instead (which can currently be done with Shift + Enter).
![preview](https://kxrfsnhxqitzsegngyki.supabase.in/storage/v1/object/public/uploads/sMUveF6ueH.gif)

### Commit hash

6a465c1

### Branch

Production (app.revolt.chat)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by LedaThemis** [comment]
Fixed in #557
