### ISSUE TITLE
[Bug Report]Revite says mp4 file is corrupt when it isn't

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [revoltchat/revite#553]
### What happened?

Revite says an mp4 file that i sent is corrupt, however if you copy and paste the media link into mpv it runs fine.
This is not an issue that is only on my machine, since everyone else in the chat had the same issue.
Issue occurred on firefox.
![2022-03-05-1646517312_1366x768](https://user-images.githubusercontent.com/76877633/156901112-993b8775-20a5-4a39-a81b-6475ff7a516f.png)

Message link:
https://nightly.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01F7ZSBSFHCAAJQ92ZGTY67HMN/01FXE02A5YFQZ5KB2BHAE0JYPT

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

6a465c1c08208f48f781116bf6895b97b1256a10

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Media resource https://autumn.revolt.chat/attachments/PxGiVo7OYYT7rPohG5Y4ivsEMtdLG4hTFbNXZPS3gk?width=720 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: mozilla::SupportChecker::AddMediaFormatChecker(const mozilla::TrackInfo&)::<lambda()>: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Zomatree** [comment]
This is an issue with firefox and will not be fixed by mozilla, see https://bugzilla.mozilla.org/show_bug.cgi?id=YUV444.
Use a differant video format that firefox is able to decode,
