### ISSUE TITLE
[Bug Report] Pasted emojis dont work in microsoft edge

### ISSUE THREAD

**Issue by FanMclaine** [revoltchat/revite#559]
### What happened?

Read title. 
![image](https://user-images.githubusercontent.com/66262586/157842497-c7e1322f-eec2-4f21-b4b3-ba04475914d3.png)

Using all emoji packs still dont work although it works on discord even using the emoji pack of discord dont work

Sorry if my english is bad, I'm listening to Eminem at the time of writing this.

### Branch

Production (app.revolt.chat)

### Commit hash

i dunno

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Tracking Prevention blocked access to storage for https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcHvHbA0jmLm7C2A1mt7sqUs9oZyMZ6ELCBQ&usqp=CAU.
app.revolt.chat/:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
api.revolt.chat/bots/01FCXF8V6RDKHSQ3AHJ410AASX/invite:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 403 ()
api.revolt.chat/bots/01FCXF8V6RDKHSQ3AHJ410AASX/invite:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 403 ()
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
This is expected, Unicode emojis are not handled by Revite.
You can open another issue for handling Unicode emojis (and converting them) if that's something you want considered.
