### ISSUE TITLE
Can't authorize microphone

### ISSUE THREAD

**Issue by stemy2** [revoltchat/revite#560]
Hello,

When i give to my browser the authorization to access to my microphone, the only change is that i can select "default audio device" in the microphone selector. The "headphone/earphones" selector remains empty and if i close the settings, i can't select a microphone anymore.

![Screenshot_20220209_125113](https://user-images.githubusercontent.com/22192600/153196093-9baddbd0-0f6c-4e66-bd03-5dd8addf9d4a.png)
![Screenshot_20220209_125203](https://user-images.githubusercontent.com/22192600/153196115-c21fcaa6-594d-4199-a898-b6ada3f9a83a.png)
![Screenshot_20220209_125305](https://user-images.githubusercontent.com/22192600/153196142-b6c099b8-48dd-4c72-be1b-f84d9b936f93.png)
![Screenshot_20220209_125358](https://user-images.githubusercontent.com/22192600/153196159-75cf8239-514d-4678-bfcc-5aaa76d13543.png)

**Comment by andy5995** [comment]
* OS: Manjaro 21.2.6

Installed revolt-desktop from the AUR. 

Whenever I grant permissions to my audio devices and then back out of the settings menu, the audio settings revert to the default (no permissions).

b53d3bc (master)
Nightly 1.0.1
Native: 1.0.5
API: 0.5.3-7
revolt.js: 6.0.2

possibly related: https://github.com/revoltchat/revite/issues/242

**Comment by ryannathans** [comment]
Same issue with flatpak revolt on Pop OS 22.04 
![image](https://user-images.githubusercontent.com/1307375/194736854-e8fff395-298c-43fc-8cfa-9608a7837eaa.png)

**Comment by candroid-man** [comment]
Same issue on Fedora 37, using Flatpak

**Comment by HaqtanEfe** [comment]
It is still happening to me.
I am using Windows 11.
