### ISSUE TITLE
iOS 15 firefox can’t upload images to personal chats 

### ISSUE THREAD

**Issue by pherwaniharsh** [revoltchat/revite#563]
### What happened?

Tried uploading an image to a friend on personal chat while using revolt on the Firefox browser, pressed “return” on my iPad keyboard and yet it didn’t share the image with the friend and instead kept skipping a line space in the chatbox. 

### Branch

Production (app.revolt.chat)

### Commit hash

[d01b9ca](https://github.com/revoltchat/revite/commit/d01b9cae4083d08ec1e071c52dbcabf7593cf74b)

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Your Shift key is probably stuck on - in future, try untapping it.

**Comment by pherwaniharsh** [comment]
Thanks!
