### ISSUE TITLE
[Bug Report] Revolt Domains Are Identified As External Domains

### ISSUE THREAD

**Issue by Infiniticity** [revoltchat/revite#566]
### What happened?

![image](https://user-images.githubusercontent.com/79257339/159674055-87ca581d-baa1-4d08-93d6-fb1ad5ff054e.png)
![image](https://user-images.githubusercontent.com/79257339/159674088-df9b337f-405b-4e16-9d6c-0455927d9d74.png)

### Branch

Production (app.revolt.chat)

### Commit hash

[d01b9ca](https://github.com/revoltchat/revite/commit/d01b9cae4083d08ec1e071c52dbcabf7593cf74b) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 0.5.3-1
API: 0.5.3-alpha.16
revolt.js: 5.2.7

### What browsers are you seeing the problem on?

Brave

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
