### ISSUE TITLE
[Bug Report] Codeblock inserting messages outside of tilda when on same line

### ISSUE THREAD

**Issue by an-dyy** [revoltchat/revite#568]
### What happened?

**USING BRAVE**
When sending codeblocks, if a message is on the same line as the last set of tildas, it will insert the messsage into the codeblock.

Input:
![image](https://user-images.githubusercontent.com/67347459/159819200-2547e758-0376-4deb-8c31-654dd25d4263.png)

Output: 
![image](https://user-images.githubusercontent.com/67347459/159819305-04a20801-f9d1-4815-a36d-815cce70f907.png)

Additionally, while reproducing this bug, I noticed that an incomplete codeblock (not using complete set of tildas) still produces a completely valid codeblock.

![image](https://user-images.githubusercontent.com/67347459/159819612-4ceea1a5-a50f-474f-b3d3-cc31a76b1d8f.png)
![image](https://user-images.githubusercontent.com/67347459/159819644-3186c52b-29ef-4550-8666-84e4f25772db.png)

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

d01b9cae4083d08ec1e071c52dbcabf7593cf74b

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Relevant log output

```shell
N/A
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Markdown is handled through [markdown-it](https://github.com/markdown-it/markdown-it) and follows CommonMark spec. I'm not sure if this can be classed as a bug and is accepted in the spec, otherwise an issue on that repo would make more sense.
