### ISSUE TITLE
[Bug Report] Bug Report form has a misspelled link, link in settings should link to form

### ISSUE THREAD

**Issue by LeviOP** [revoltchat/revite#570]
### What happened?

While clicking on the link in the bug report issue template, I've just seen that it links to https://gihtub.com/revoltchat/desktop (should be github)
![image](https://user-images.githubusercontent.com/35459268/160218083-ce5014b2-7b98-46fc-81ca-37fbcc63d4ac.png)

I'd also like to suggest that the link for submitting issues link to the bug report template page instead of the blank new issue page (https://github.com/revoltchat/revite/issues/new?assignees=&labels=bug&template=bug.yaml&title=%5BBug+Report%5D instead of https://github.com/revoltchat/revite/issues/new) 
![image](https://user-images.githubusercontent.com/35459268/160218176-b4e5d24f-2f23-461c-916f-d521a9cc478a.png)

### Branch

Production (app.revolt.chat)

### Commit hash

[f9f0d5c](https://github.com/revoltchat/revite/commit/f9f0d5c55a6a3e61319a3ed7cb39a2e13ac536f8) [(master)]

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
