### ISSUE TITLE
No notification for calls

### ISSUE THREAD

**Issue by marco-trovato** [revoltchat/revite#581]
I noticed there are notification for messages but not for incoming voice calls.

To be coherent with all other messengers (all of them do ring: _Google Duo, Discord, Telegram, Matrix clients_),
there should be at least an option to have a notification for joining the incoming private voice chats requests.

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
