### ISSUE TITLE
[Bug Report] Bot Banner Size

### ISSUE THREAD

**Issue by TheClashFruit** [revoltchat/revite#585]
### What happened?

I tried to upload a banner for my bot which is under 6 MB.

![NVIDIA_Share_Zn7aCcM033](https://user-images.githubusercontent.com/55049569/163707183-8bda38d9-a70e-460c-b9b6-2d1b70f67626.png)

### Branch

Production (app.revolt.chat)

### Commit hash

[cf049bd](https://github.com/revoltchat/revite/commit/cf049bd4ee1ccd6f630a09345d104184091294da) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 0.5.3-1
API: 0.5.3-alpha.16
revolt.js: 5.2.7

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by janderedev** [comment]
The file is in fact larger than 6MB. [Windows is lying to you](https://www.nextofwindows.com/gb-gigabyte-and-mb-megabyte-is-not-what-you-think-is-in-windows) - The displayed size is in MiB, and 5.76 MiB is ~6.04MB. You could try converting the file to JPG to reduce the filesize.

I'm going to close this - Feel free to reopen if I'm wrong :)
