### ISSUE TITLE
Mobile PWA brings up message about an error, page becomes unresponsive. 

### ISSUE THREAD

**Issue by CorruptedPlazma** [revoltchat/revite#586]
Screenshots of the problem -
![Screenshot_20220419-191950_Chrome](https://user-images.githubusercontent.com/88416096/164117228-a50fbf13-abd2-4752-ac2f-bdedc3bc07bc.jpg)

https://user-images.githubusercontent.com/88416096/164117248-da4c8e36-5671-492e-a654-d81e6e3860ff.mp4

Reloading the PWA and clearing cache/data has not worked. Anywhere on the page where touch input would be is completely non-functional.

**Comment by GenericNerd** [comment]
Can confirm this behaviour is similar on desktop and web apps. This is likely due to an outage with the API so I'd wait about an hour before trying again.

**Comment by insertish** [comment]
Issue with error modal has been fixed.
