### ISSUE TITLE
bug: Reply button in message toolbar appears even if you don't have the Send Messages permission

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revite#589]
### What happened?

Similar to #265, the Reply button appears on the message toolbar even if you don't have the Send Messages permission.

![image](https://user-images.githubusercontent.com/42586271/165372502-539e50d1-7b21-4fc8-af87-e19bc6e60e43.png)

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

147880a447cd6b79a2dd6b0d1cd7d4b5fd90bee8

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
