### ISSUE TITLE
[Bug Report] NSFW buttons aren't working

### ISSUE THREAD

**Issue by account0123** [revoltchat/revite#590]
### What happened?

When i try to enter to a NSFW channel and prompt appears.
![Captura de pantalla de 2022-04-26 16-04-16](https://user-images.githubusercontent.com/27470405/165382999-297f06ba-0ea4-4555-a811-6a3880b774a9.png)
Neither of the 2 buttons do anything. So, i cannot access to these channels.

This bugs occurs in app.revolt.chat & nightly.revolt.chat
In desktop, the only button working is go back.

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

i do not know, maybe d01b9cae4083d08ec1e071c52dbcabf7593cf74b

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by janderedev** [comment]
I think your theme is hiding it, but there's a checkbox next to the slightly off center text which you have to press before the confirm button works. Not sure why the "Go back" button doesn't work though.

**Comment by account0123** [comment]
I removed the theme and...
![Captura de pantalla de 2022-04-26 19-43-30](https://user-images.githubusercontent.com/27470405/165410363-1368938c-d73e-406a-ba50-f5e2c6fac63f.png)
both buttons are working properly :D (maybe the theme i have applied was outdated or something like that)

**Comment by insertish** [comment]
Closing this issue.
