### ISSUE TITLE
[Bug Report] Member list does not appear to render

### ISSUE THREAD

**Issue by janderedev** [revoltchat/revite#595]
### What happened?

![image](https://user-images.githubusercontent.com/26145882/166105693-bfd2b9a3-e902-4102-bdc5-d2de33bfb6f5.png)

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

[b2a9cfd](https://github.com/revoltchat/revite/commit/b2a9cfd987bf98ce455671afd26a179446c2b68a) [(master)](https://github.com/revoltchat/revite/tree/master)

### Relevant log output

```shell
(none)
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by janderedev** [comment]
Same for the invites and bans tab

**Comment by insertish** [comment]
Broke in #588, reverted in https://github.com/revoltchat/revite/commit/a66e96677f3a77fc823de738ccb0e989330e3158.
