### ISSUE TITLE
Invite join button returns undefined

### ISSUE THREAD

**Issue by realShamlol** [revoltchat/revite#597]
I copied an invite from someone on Discord so that I could join their Revolt server, when I copied the link, pasted it on Revolt, and clicked the join button, I got an error and checked the console and it was trying to take me to an invite ending with /undefined. 
![image](https://user-images.githubusercontent.com/80943664/166144413-bc6a754d-3918-47ba-9213-03841e485fa1.png)
![image](https://user-images.githubusercontent.com/80943664/166144460-c0c12fba-dc90-43a6-b9ac-3dc2dbd841c3.png)
Specifications:
- Nightly 0.5.3-1
- Revolt Desktop App [08e1db6](https://github.com/revoltchat/revite/commit/08e1db6d3528e55712749667842bc399bbca91a5) [(master)](https://github.com/revoltchat/revite/tree/master)
- Windows 10 Pro
- Asus VivoBook

**Comment by insertish** [comment]
Please switch to the stable branch of Revolt in settings.

**Comment by realShamlol** [comment]
Also when creating an invite, it returns /invite/undefined as well, and also when clicking the link and clicking Accept Invite with this(image below), it says /undefined as well. However these things seem to work on the Revolt site but not the Desktop app. And yes I have tried reloading revolt
![image](https://user-images.githubusercontent.com/80943664/166144637-757bd309-a556-4cce-88d3-ac36ecd1dea1.png)

**Comment by realShamlol** [comment]
> Please switch to the stable branch of Revolt in settings.
> 
> ![image](https://user-images.githubusercontent.com/38285861/166144571-8e47fa43-6f2c-49c3-a775-73b19b9a120e.png)
> 
> ^ turn this off

Alright.
