### ISSUE TITLE
tester server moderator 'insert' is bugged

### ISSUE THREAD

**Issue by dotdlew** [revoltchat/revite#599]
the bot banned me from the tester server for reporting a slur in the bot commands and asking for a command rename

how is this a bannable offence?

please adjust the bot to be less sensitive

**Comment by Rexogamer** [comment]
(For context, the command in question was `-gaytext`, which returns the message in rainbow Katex text.)

**Comment by insertish** [comment]
Given the wave of trolls we just had, I can only assume you're either part of that group and persistent or just plain misguided.

I'll give you the benefit of the doubt.
Well I keep trying to, but looking back on what you said really does come across as trying to bait us, for example:

> or do i need to report this server?

There's two things wrong here obviously:
- The server is quite clearly labeled that it's operated as part of the project

**Comment by insertish** [comment]
My GitHub just broke but ok
