### ISSUE TITLE
[Bug Report] Image sending when image already sent (i have no other words to describe this)

### ISSUE THREAD

**Issue by FanMclaine** [revoltchat/revite#600]
### What happened?

![image](https://user-images.githubusercontent.com/66262586/167075557-93dddf13-4490-4b54-8d77-f24b0e0d096a.png)
Pasted image still trying to send when image is already sent

(apologies for my bad english and the mug root beer)

### Branch

Production (app.revolt.chat)

### Commit hash

this?
![image](https://user-images.githubusercontent.com/66262586/167075811-d5a98109-f228-4524-9b9c-33006baee499.png)

### What browsers are you seeing the problem on?

Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by janderedev** [comment]
This issue is API related and already fixed in an upcoming version. For some reason the server never bothers to send a response in certain circumstances, resulting in the message getting stuck like this.

**Comment by insertish** [comment]
Resolved by https://github.com/revoltchat/revolt/issues/322.
