### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by peepo5** [revoltchat/revite#601]
### What happened?

When my internet disconnected and reconnected again, Revolt app would not allow me to access channels or members list, it said that I need internet to read, but I had a connection when I turned it back on. It should check every now and then if internet is back.

Refreshing 'fixes' the issue, but it can still happen again the same way.

### Branch

Production (app.revolt.chat)

### Commit hash

[83a3585](https://github.com/revoltchat/revite/commit/83a3585940bb7400e2906a498059884f4c13d3dd)

### Relevant log output

```shell
None
```

### Desktop

- [X] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Did a reload fix this issue?

**Comment by peepopoggers** [comment]
@Rexogamer yes, i forgot to mention that

**Comment by insertish** [comment]
Commit is pre-API update, closing as invalid.
Use CTRL + F5 / R to force update your client.

**Comment by peepopoggers** [comment]
Please re-open, I still have this issue:
![image](https://user-images.githubusercontent.com/72892531/167272220-be96bf0a-aa99-4e24-be06-6a440c67e97d.png)
Hash: [2d5128f](https://github.com/revoltchat/revite/commit/2d5128fca8fa45e1d3cfb4b357e100e4bacbf961)
