### ISSUE TITLE
feature request: allow configuring custom discover tab or hiding it

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#602]
### What do you want to see?

Allow hiding the discover tab or otherwise hiding it completely.

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by lswencn** [comment]
Open source, please respect everyone

**Comment by Rexogamer** [comment]
...? We don't have any current plans to open source Discovery - if this wasn't what you meant, my apologies
