### ISSUE TITLE
Bug in the "discover revolt"

### ISSUE THREAD

**Issue by looney2001** [revoltchat/revite#606]
Hey. When I go to Discover Revolt and click on a server it shows me: "Invalide invite, the invite may not exist or you don't have permission to join". This appears with any server among the Discover servers. The bug persists even if I relaunch the page

**Comment by DoruDoLasu** [comment]
commenting on that: the invite links are like:
https://app.revolt.chat/invite/01FN503VZA1FT0JN1PHZV6S62C
the last part is not a valid invite code, but instead the server id

**Comment by Rexogamer** [comment]
Duplicate of revoltchat/delta#156
