### ISSUE TITLE
bug: the friend requests in profile don't work for some reason

### ISSUE THREAD

**Issue by DoruDoLasu** [revoltchat/revite#607]
### What happened?

![image(1)](https://user-images.githubusercontent.com/100388457/167274978-40dccffa-573b-44fd-b820-6f0323b409d5.png)

### Branch

Production (app.revolt.chat)

### Commit hash

ad5128f

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
I don't know
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by VeiledProduct80** [comment]
Also seeing this issue on chrome so it's not firefox specific

**Comment by spaceyspacestar** [comment]
Also seeing it on the desktop client of revolt
