### ISSUE TITLE
bug: Theme not respected on sidebar

### ISSUE THREAD

**Issue by noobfletcher1** [revoltchat/revite#608]
### What happened?

Self Explanitory

### Branch

Production (app.revolt.chat)

### Commit hash

2d5128f

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
This is slightly vague - which part of the sidebar are you referring to? Taking a look, it all looks correctly themed on my end (bar the "current server" indicator, which is known to be incorrect).

**Comment by noobfletcher1** [comment]
The popout for the the server icon

**Comment by noobfletcher1** [comment]
![image](https://user-images.githubusercontent.com/51877146/168668471-6322e307-04d4-4207-a696-529bd4e72179.png)
image for reference

**Comment by Kapeet** [comment]
was this already fixed?

**Comment by Rexogamer** [comment]
Not sure when - although it was probably during the work on server reordering - but this has been fixed.
