### ISSUE TITLE
bug: not possible to reorder channels in Uncategorized

### ISSUE THREAD

**Issue by TibbeD** [revoltchat/revite#610]
### What happened?

When I tried to re-order some channels on my guild in Uncategorized, it didn't work, while it does work in all (other?) categories

### Branch

Production (app.revolt.chat)

### Commit hash

[`eb1bd27`](https://github.com/revoltchat/revite/commit/eb1bd27ec0e491c8a747c4bb442eb7dfb0aa6350)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
For context, this is not implemented yet.

**Comment by insertish** [comment]
This will be implemented in new client.

Closing due to rewrite, https://github.com/revoltchat/frontend.
