### ISSUE TITLE
feature request: add syntax highlighting for files

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revite#611]
### Discussed in https://github.com/orgs/revoltchat/discussions/363

<div type='discussions-op-text'>

<sup>Originally posted by **SlenPlayz** May  8, 2022</sup>
So discord has this thing where when you upload a file with code in it ex a .js file the preview is also syntax highlighted I think this wld be a great addition to revolt as well + it shldnt be too hard to implement considering stuff like highlight.js exist

Revolt
![image](https://user-images.githubusercontent.com/67079195/167286613-75741357-6e57-4225-b318-3596303efe84.png)

Discord:
![image](https://user-images.githubusercontent.com/67079195/167286651-cbdfd661-253c-4f11-8a8b-cd2320a4c1d4.png)
</div>

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
