### ISSUE TITLE
feat: limit nested quote depth

### ISSUE THREAD

**Issue by yonipy** [revoltchat/revite#622]
![image](https://user-images.githubusercontent.com/75043612/161546620-2b69818b-1ee5-440d-ae33-05be9b80bd37.png)

Is this meant to be a feature ?

**Comment by LedaThemis** [comment]
Fixed in 448722225ea7a6591a95e1aa2b568acb0a7743ca, 4a85dd69cf66dcbf654cd67ba11db80c033ea90e. (limited maximum quote depth to 3)
