### ISSUE TITLE
issue: dependabot security updates not compatible with yarn v3

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#626]
PRs created by Dependabot use the original `yarn.lock` format so they will just break the project.

Remote issue:
- [x] https://github.com/dependabot/dependabot-core/issues/1297

Some solutions brought up in the issue:
- [Run `yarn up` on a cronjob and create PRs through that](https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-670292585), though this could potentially introduce API breaking changes
- [Use the existing Dependabot PRs and make them work](https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-671131912)
- [Alternative solution by styled-icons team](https://github.com/styled-icons/styled-icons/blob/main/.github/workflows/dependabot.yml)

**Comment by Rexogamer** [comment]
Possible alternative: investigate switching to [Renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate/) - it includes Yarn 3, can bundle updates and more

**Comment by insertish** [comment]
Now supports yarn v3
