### ISSUE TITLE
bug: 400 Status Code trying to change bot user data

### ISSUE THREAD

**Issue by ksIsCute** [revoltchat/revite#629]
### What happened?

While changing the bots banner, profile photo, and bio, I kept getting errors and status codes of 400 (bad request) the video below is my experience with this while trying to change my bots information.

### Branch

Production (app.revolt.chat)

### Commit hash

[cca97f9](https://github.com/revoltchat/revite/commit/cca97f9bb9202a290009d26c8d38ec1e606e9e14) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 0.5.3-1
API: 0.5.3-2
revolt.js: 6.0.0-rc.26

(this is what i got from the settings idk if its wrong just tell me)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
api.revolt.chat/users/@me:1          Failed to load resource: the server responded with a status of 400 ()
api.revolt.chat/bots/create:1          Failed to load resource: the server responded with a status of 400 ()
api.revolt.chat/bots/create:1          Failed to load resource: the server responded with a status of 400 ()
api.revolt.chat/users/@me:1          Failed to load resource: the server responded with a status of 400 ()
api.revolt.chat/users/@me:1          Failed to load resource: the server responded with a status of 400 ()
api.revolt.chat/bots/01FZJSD2B22RA9MMHVBYY57T2B:1          Failed to load resource: the server responded with a status of 400 ()
api.revolt.chat/users/@me:1          Failed to load resource: the server responded with a status of 400 ()
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by ksIsCute** [comment]
https://imgur.com/a/CuzuG7S (proof of bug)

**Comment by CorpseDev** [comment]
yeah same

![Wew400](https://user-images.githubusercontent.com/88591830/168484093-30b3c5b7-2e3d-46e2-aad1-49026b596371.png)

**Comment by CorpseDev** [comment]
![image](https://user-images.githubusercontent.com/88591830/168799358-b1dd71a7-3ba7-44d4-883b-71cb12883cdc.png)

**Comment by CorpseDev** [comment]
> this is still a bug :trollface:

:trollface:
