### ISSUE TITLE
Group Bug

### ISSUE THREAD

**Issue by ayberk0300** [revoltchat/revite#63]
![unknown](https://user-images.githubusercontent.com/61204721/129202865-199bc0d6-7107-469f-a575-9ed5ab2345d6.png)

I'm the one who added her to the group, but she says she added me to the group.

**Comment by janderedev** [comment]
Seems like a translation issue. See [Turkish](https://weblate.insrt.uk/translate/revolt/web-app/tr/?checksum=541cbf34962dca28&sort_by=-priority,position) and [English](https://weblate.insrt.uk/translate/revolt/web-app/en/?offset=1&q=app.main.channel.system.added_by&sort_by=-priority%2Cposition&checksum=) translation.

**Comment by janderedev** [comment]
Has been fixed.
