### ISSUE TITLE
bug: "AN ERROR OCCURED! See console." When uploading images.

### ISSUE THREAD

**Issue by nsde** [revoltchat/revite#632]
### What happened?

![image](https://user-images.githubusercontent.com/67185896/168493614-cd83a59d-4efd-49a1-9f53-b6fc1b1a943a.png)

I tried to change a server's banner and a bot's icon (server's icon & profile icon worked)

### Branch

Production (app.revolt.chat)

### Commit hash

https://github.com/revoltchat/revite/commit/cca97f9bb9202a290009d26c8d38ec1e60
[(master)]
(https://github.com/revoltchat/revite/tree/master)
Nightly 0.5.3-1
API: 0.5.3-2
revolt.js: 6.0.0-rc.26

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Error in parsing value for ‘height’.  Declaration dropped.
Error in parsing value for ‘fill’.  Declaration dropped.
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Partially fixed in https://github.com/revoltchat/delta/pull/163.
Partially duplicate of https://github.com/revoltchat/revite/issues/629.
