### ISSUE TITLE
bug: web app does not respect my browser text size

### ISSUE THREAD

**Issue by ooliver1** [revoltchat/revite#635]
### What happened?

revolt - ![image](https://user-images.githubusercontent.com/34910574/168674978-3dfb3c2a-3711-4577-8a07-90371a03bbe8.png)
discord - ![image](https://user-images.githubusercontent.com/34910574/168675020-c11f34d3-1af6-4f66-a5b1-3b3869262eea.png)

revolt does not respect the browser font scaling/provide a slider to change font size
the browser font and `html {font-size: ...}` affects only a few elements which puts everything out of proportion

browser: irrelevant but opera - chromium

### Branch

Production (app.revolt.chat)

### Commit hash

https://github.com/revoltchat/revite/commit/f8e67af962c60828addd24cecbc2c746d1adbb44

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
