### ISSUE TITLE
feature request: embed colors

### ISSUE THREAD

**Issue by ksIsCute** [revoltchat/revite#636]
### What do you want to see?

I made a little preview in html + css, i literally just needed to edit one thing in the embeds style tag
![example](https://user-images.githubusercontent.com/92867218/168852594-6336189b-ca00-40f4-8e3b-a2f8ba14ae0c.png)
To accomplish this you only need to edit the `border-inline-start-color` value of the embed div (the one using `_embed_1912h_1 _website_1912h_12`). Can this be accomplished by just getting the `theme-color` from meta tags (from websites)? As its already a thing in revolt.py and revolt.js (i think).

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by ksIsCute** [comment]
![image](https://user-images.githubusercontent.com/92867218/168858952-905eb3aa-1291-440d-adbc-5537166ef869.png)
also quick update i made the preview look better

**Comment by ksIsCute** [comment]
still dont get why january is overlapping embeds

**Comment by Rexogamer** [comment]
> still dont get why january is overlapping embeds

What exactly do you mean?

**Comment by insertish** [comment]
Feature already exists, need more clarification.
Re-open if unsolved.
