### ISSUE TITLE
bug: stacked embeds on edited message

### ISSUE THREAD

**Issue by ksIsCute** [revoltchat/revite#637]
### What happened?

![image](https://user-images.githubusercontent.com/92867218/168871030-645a5649-00c2-4f4a-8ac0-baa70374b7fe.png)
when editing a message it looks normal on the client side, but when you refresh you can see what other see, the stacked embeds.

### Branch

Production (app.revolt.chat)

### Commit hash

[f8e67af](https://github.com/revoltchat/revite/commit/f8e67af962c60828addd24cecbc2c746d1adbb44) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 0.5.3-1
API: 0.5.3-2
revolt.js: 6.0.0-rc.26

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
I forgot when this was fixed but this was fixed.
