### ISSUE TITLE
bug: Transparent Server Icons and User Profile Pictures

### ISSUE THREAD

**Issue by Pokegamer129** [revoltchat/revite#638]
### Transparent Server Icons and Profile Pictures

I don't know how it happened, but all of the server icons and profile pictures of users are currently transparent and are hard to view, I don't know how to fix it, I tried uninstalling and reinstalling the app, and I couldn't find any settings that would change the opacity of the items.

How would I fix this?

**Comment by Pokegamer129** [comment]
> Can you share a screenshot?

Yeah sure, give me a sec

**Comment by Pokegamer129** [comment]
![Screenshot_20220517-102120_Samsung Internet](https://user-images.githubusercontent.com/32755415/168882107-79eda23f-4ada-4c34-ac2a-3b30c794a5d2.jpg)

**Comment by Pokegamer129** [comment]
I've solved some parts. 

It'll become transparent after messages are sent, and servers go back to normal after marking all as read. However, my profile pic, as well as DMs are still transparent and idk why

**Comment by Pokegamer129** [comment]
![Screenshot_20220517-170255_Samsung Internet](https://user-images.githubusercontent.com/32755415/168931335-1596520c-bfaa-4bea-b209-96deb74adcd1.jpg)
Here is another ss of transparent PFPs where it doesn't make sense

**Comment by I2rys** [comment]
If you are using a custom theme maybe It's the problem?

**Comment by Pokegamer129** [comment]
> If you are using a custom theme maybe It's the problem?

I am currently not using a custom theme, however, I also noticed for some reason, colors are different across Mobile and PC

**Comment by I2rys** [comment]
> > If you are using a custom theme maybe It's the problem?
> 
> I am currently not using a custom theme, however, I also noticed for some reason, colors are different across Mobile and PC

The colors should also be the same(Default). If the one in your PC looks like this the default theme but your Mobile is different the problem might be is your Mobile somehow.
![image](https://user-images.githubusercontent.com/87125939/172549433-fbd12fdc-d7ad-4a6f-b41b-ce91ee30cf80.png)

**Comment by insertish** [comment]
From a quick glance I do notice that SVG masks are not working in the screenshot and it could point to an outdated browser.
Is there any more information about the device?

**Comment by Pokegamer129** [comment]
@insertish I am using a Samsung Galaxy S22+, let me know what other specifics you need!

**Comment by Rexogamer** [comment]
What browser (and more important what version of said browser) are you using?

**Comment by Pokegamer129** [comment]
@Rexogamer The browser I regularly use is Opera GX, and I am using the latest version. I use the Revolt app on Mobile however, and whatever browser that uses is what that uses

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.

Afaik this is due to some sort of auto-dark mode, nothing we can personally do about, you have to disable it yourself.
