### ISSUE TITLE
bug: Disappering badges 

### ISSUE THREAD

**Issue by noobfletcher1** [revoltchat/revite#644]
### What happened?

I was chatting and my early adopter badge disappered

### Branch

Production (app.revolt.chat)

### Commit hash

73d51a3

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
What is your ID?

**Comment by noobfletcher1** [comment]
01EXAG0ZFX02W7PNQE7W5MT339 and here some proof
Before:
![image](https://user-images.githubusercontent.com/51877146/169648077-f59bc64c-ef7c-459d-a50b-ddc42166b89f.png)
After:
![image](https://user-images.githubusercontent.com/51877146/169648106-9cf2a400-3221-4669-99fd-93eb0240fd68.png)

**Comment by noobfletcher1** [comment]
happened again
