### ISSUE TITLE
bug: Desktop UI on large tablets is great, except the keyboard obstructs the message preview

### ISSUE THREAD

**Issue by Inderix** [revoltchat/revite#646]
### What happened?

Viewing the website on a tablet, specifically in my use case a Fire HD 10, results in the desktop ui (which is good!). Opening the keyboard to type results in the site not adjusting accordingly, meaning any content that was where the keyboard is can't be seen, including the message input preview. 
![Screenshot_20220522-212839](https://user-images.githubusercontent.com/88416096/169726869-dcc3ecce-1023-4efc-a722-adcfc791c87a.png)

### Branch

Production (app.revolt.chat)

### Commit hash

6fcdbd1

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Can confirm something similar also happens on iPadOS - the message bar is partially covered by the (full-size) keyboard:
![image](https://user-images.githubusercontent.com/42586271/169859416-c25305dc-c189-42a8-8a55-d52bf3a15193.png)

**Comment by CorruptedPlazma** [comment]
Found an interesting little thing about the Android side: Problem appears to have been because I was forcing the system immersive mode to run (to hide the status bar and navigation bar). Disabling immersive mode appears to resolve it.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
