### ISSUE TITLE
bug: no way to change things such as unmuting

### ISSUE THREAD

**Issue by Gamecat178** [revoltchat/revite#647]
### What happened?

![image](https://user-images.githubusercontent.com/97407708/169185941-9a94ff3a-3b22-4f97-b496-1236a9146b76.png)
no way to usably using the voice chat in current state

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
