### ISSUE TITLE
bug: server icon sometimes taking longer to load when reordered

### ISSUE THREAD

**Issue by stationaryStation** [revoltchat/revite#649]
### What happened?

Icon not updating when moved too many times

Using revolt-desktop-git

### Branch

Production (app.revolt.chat)

### Commit hash

bdf741e

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by stationaryStation** [comment]
Relevant video

https://user-images.githubusercontent.com/81704775/170786921-a8bf05b0-47bd-4f2e-bcdb-021a57f604af.mp4

**Comment by I2rys** [comment]
**Icon not updating when moved too many times** I'd say It just updates too slow and the word **Icon not updating** does not match the problem because It means the Icon is really not updating.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

Also I think this might not be an issue with the new dnd.
