### ISSUE TITLE
feature request: Make chat less cramped and more consistently spaced overall

### ISSUE THREAD

**Issue by l4ssc** [revoltchat/revite#652]
### What do you want to see?

Revolt tends to be inconsistently and too closely spaced in chat and this results in readability issues for me. I have been experimenting with Revite myself to improve this, but because I am not too experienced with web development as a whole I figure I'm probably not the person for the job (though I'd be glad to PR what I have and eventually improve it to the point of Being Good!)

**Before changes (using Inter as the selected font):**
![](https://user-images.githubusercontent.com/72284051/170951150-e5d79892-de3f-4b4e-ab9b-be9296646be0.png)

**After personal changes in source (just as a general idea of what I had in mind):**
![](https://user-images.githubusercontent.com/72284051/170949743-d68cf596-51c0-4204-b49b-7a31aede1768.png)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
