### ISSUE TITLE
bug: Markups not applying unless separated by a space

### ISSUE THREAD

**Issue by Lizband** [revoltchat/revite#653]
### What happened?

When typing `Coolio*!*` the expected result is to have the string `Coolio!` with italic punctuation. Instead the result is the message `Coolio*!*` with the asterisks still visible and with no markup applied to the text.

### Branch

Production (app.revolt.chat)

### Commit hash

12b9716

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
This is likely an issue with markdown-it.

**Comment by insertish** [comment]
Switched to remark at some point.

Closing due to rewrite, https://github.com/revoltchat/frontend.
