### ISSUE TITLE
bug: Unable to click on emojis while editing user bio

### ISSUE THREAD

**Issue by ksIsCute** [revoltchat/revite#654]
### What happened?

I typed in a custom emoji and went to click it but it didnt work
![image](https://user-images.githubusercontent.com/92867218/171045533-fec45fbd-cf3d-440e-8b3f-c67cec4488fb.png)

### Branch

Production (app.revolt.chat)

### Commit hash

[12b9716](https://github.com/revoltchat/revite/commit/12b97160433151c188b077bd3e85fc2ee35bbd99) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 0.5.3-1
API: 0.5.3-5-patch.2
revolt.js: 6.0.2

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
