### ISSUE TITLE
bug: the min-width: 450px in the Modal component causes inconsistencies

### ISSUE THREAD

**Issue by gigantino** [revoltchat/revite#657]
https://github.com/revoltchat/revite/blob/12b97160433151c188b077bd3e85fc2ee35bbd99/src/components/ui/Modal.tsx#L124
This property seems to be causing a design inconsistency in the pending-requests modal which can be found in the friends page. The margin on the left is much smaller than the one on the right.

![Screenshot 2022-06-03 164026](https://user-images.githubusercontent.com/29411889/171876682-c0394f6f-eddd-4b41-ac26-c276c033b4a7.png)

The Modal component might need some work to avoid problems like this in the future (maybe using flexbox?). Removing this property isn't an option since while it does fix this modal in particular it's actually needed in the vast majority of them.

**Comment by insertish** [comment]
![image](https://user-images.githubusercontent.com/38285861/173625161-87e6a8cd-cb00-4469-9143-4cebc5d7468d.png)
