### ISSUE TITLE
Voice Settings bug 

### ISSUE THREAD

**Issue by Logwn** [revoltchat/revite#662]
Whenever you click off and back on the voice settings it will always say you need to grant permission even if permission is already granted.

**Comment by I2rys** [comment]
I tried to reproduce this and It does not seem to work both on web & desktop.

**Comment by DylanLogan2581** [comment]
This issue still exists. Every time I open "Voice Settings" I am prompted to grant permission to access audio settings.

**Comment by henceiusegentoo** [comment]
Still is a problem on my device

**Comment by Rexogamer** [comment]
Duplicate of #459.
