### ISSUE TITLE
bug: Too many message request

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#671]
So If you spam message until it reaches to the point where your messages are blocked with the "TOOMANYREQUESTS" message. It's impossible to delete it and If you chat again after the rate limit your messages are sent above it, it's **fixed** position and If you keep spamming even though you are rate limited you won't be able to see new messages coming as they will all be on the top of the errors.

https://user-images.githubusercontent.com/87125939/172559520-e33a337c-9e9e-47c8-8097-95f6f8f50950.mp4

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
