### ISSUE TITLE
bug: Friends does not load in Group invite

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#681]
It's just empty, to be precise the names & profile pictures does not show.

![image](https://user-images.githubusercontent.com/87125939/173270413-5d1f2533-8b81-4bfd-a135-9e8f5d3940d9.png)

**Comment by insertish** [comment]
![image](https://user-images.githubusercontent.com/38285861/173625113-e148c168-c88d-4e1e-88d3-124a3b514cf2.png)

I may move it once I start rewriting these modals.
