### ISSUE TITLE
bug: Server banner colors bleed into the glassy blur beside it

### ISSUE THREAD

**Issue by Inderix** [revoltchat/revite#682]
### What happened?

Appears most on bright banners (such as in my own server). Colors of the banner bleed over into the glass background of the channel information seen at the top of each channel. It looks quite odd, so I assume it's a visual error.
![image](https://user-images.githubusercontent.com/88416096/173548575-dbb8168d-5056-48da-b86d-55f07c03f568.png)

### Branch

Production (app.revolt.chat)

### Commit hash

[0071824](https://github.com/revoltchat/revite/commit/00718245f92000d1fc491d9953adc7d298fa5a6e)

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
