### ISSUE TITLE
bug: cannot clear custom status

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#685]
### What happened?

Clearing custom status is just ignored by the ~~server~~ client.

**Comment by LedaThemis** [comment]
@insertish, replacing
https://github.com/revoltchat/revite/blob/a190a51d0b597370e66de96f7c94592debb7705c/src/lib/ContextMenus.tsx#L370-L376
with the following
```js
case "clear_status":
    {
        await client.users.edit({ remove: ["StatusText"] });
    }
    break;
```
worked, but not sure if there are more places that needs this
