### ISSUE TITLE
Invites Are Broken

### ISSUE THREAD

**Issue by Infiniticity** [revoltchat/revite#688]
### What happened?

I have created an invite: 
![image](https://user-images.githubusercontent.com/79257339/173727640-e687a623-aa43-4cc1-8e3c-831eefa645e2.png)

When sent in chat:
![image](https://user-images.githubusercontent.com/79257339/173727733-6f6882f2-2cd5-4039-b005-a083e6994b0c.png)

After some clicks, the invite loads.

### Branch

Production (app.revolt.chat)

### Commit hash

[`a190a51`](https://github.com/revoltchat/revite/commit/a190a51d0b597370e66de96f7c94592debb7705c)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by I2rys** [comment]
The problem here was the rate limiter.

**Comment by insertish** [comment]
Could add internal rate limiter when fetching invites.
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
