### ISSUE TITLE
feature request: Use Aztec codes for barcode-based invites

### ISSUE THREAD

**Issue by erkinalp** [revoltchat/revite#689]
### What do you want to see?

Aztec codes cover less per unit data, and can be read faster than QR codes. For this reason, they are frequently used in air and railway tickets. Revolt should use them as guild/group invites.

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by du64** [comment]
This is a bad idea, because then your links only work with a specific reader, which makes inviting people to revolt harder

**Comment by erkinalp** [comment]
False, Aztec codes work in all iOS and Android versions since 2017.

**Comment by Rexogamer** [comment]
Can you scan them with the built-in scanner app? It wouldn't be a great user experience to have to download an app just to scan them.

**Comment by erkinalp** [comment]
Yes, they can be scanned with the built-in app.

**Comment by Rexogamer** [comment]
Are you sure..? I tried scanning the first code listed [here](https://en.wikipedia.org/wiki/
Aztec_Code) with the built in scanner app on iPadOS 15.6.1 but it didn't do anything - it worked in Scandit (a 3rd party scanner app) but I don't think asking users to download apps just to scan a code is a particularly great option when QR codes are more widely supported

**Comment by Rexogamer** [comment]
I'm going to close this issue for now - QR codes *work* and are widely supported, but if Aztec codes *are* faster we may considering switching to them if/when they gain wider support.
