### ISSUE TITLE
the settings icon on android and settings for servers

### ISSUE THREAD

**Issue by AnimeYarely** [revoltchat/revite#691]
so the settings icon that is below the servers well the bottom bar is kind of hiding it and it shows barely a quarter of it and when you hold servers for the settings it doesn't appear the thing that shows where you are at it just disappears

**Comment by Evilhotdog** [comment]
Could you attach a screenshot, please?

**Comment by AnimeYarely** [comment]
> Could you attach a screenshot, please?

like tha?
![Screenshot_20220710-023043_Samsung Internet.jpg](https://user-images.githubusercontent.com/69837533/178135534-cebb9eaa-dace-43ad-b42f-f3d492ab1de8.jpg)
