### ISSUE TITLE
bug: disabled-js.svg 404 Not Found

### ISSUE THREAD

**Issue by HeadcrabJ** [revoltchat/revite#701]
### What happened?

On page JavaScript is disabled, svg won't load on path https://app.revolt.chat/disabled-js.svg, code 404 Not Found

### Branch

Production (app.revolt.chat)

### Commit hash

63d5f6bb7d06660aaecb960793c25433fe67e3bb

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
