### ISSUE TITLE
bug: "Click to copy username" tooltip behind menu

### ISSUE THREAD

**Issue by Tmpod** [revoltchat/revite#704]
### What happened?

When transparency effects are turned on, the "Click to copy username" tooltip is rendered behind the profile activity menu, as show in the picture below:

![imagem](https://user-images.githubusercontent.com/35771816/174461014-4f80f3a9-1984-4de9-88d0-c05394aca91a.png)

Tested in Firefox 100.0.2 and Brave 1.39.111.

### Branch

Production (app.revolt.chat)

### Commit hash

aa99741

### What browsers are you seeing the problem on?

Firefox, Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
