### ISSUE TITLE
bug: client is null in when changing username, password, email (ModifyAccount)

### ISSUE THREAD

**Issue by LedaThemis** [revoltchat/revite#705]
### What happened?

Trying to change username, email, or password results in the following
![showcasing console with error saying "client is null"](https://user-images.githubusercontent.com/38331868/174686029-e6e0ba2a-7f4d-4511-bb0e-1de5ad326099.png)

This started happening after 6755217ad25d47c452692fff8148d2f24fd517f9

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

aa99741

### What browsers are you seeing the problem on?

Firefox, Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by I2rys** [comment]
So this was the reason why I can't change my password. This should be fixed ASAP.

**Comment by insertish** [comment]
Fiexd in cb0a5214739b8a76708dbeddda14c54118da46d5.
