### ISSUE TITLE
view change logs doesn't show all change logs

### ISSUE THREAD

**Issue by BILLPC2684** [revoltchat/revite#708]
i went to see what all updates/changes that i've missed from being absent from the platform
i saw 2FA was added and thats cool, i'll probbly do that in alittle bit but i wanted to see the full list
i checked the change logs... and there was only 1 item in the list, about the 2FA...
clearly this isn't the only one, right? 
![image](https://user-images.githubusercontent.com/16583502/174848442-bc1689fc-7f97-4471-9295-49ef92ef1c4d.png)

**Comment by insertish** [comment]
Changelogs were added with the 2FA update, if you want to read more about past updates you can check out the Updates channel on the main server (https://rvlt.gg/Testers).
