### ISSUE TITLE
bug: Call deafen & glitch

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#710]
If you unmute then deafen so you can't hear them then mute & unmute again you will be able to hear them again even though you have deafen on not just that It seems like If you spam mute & unmute It won't sync anymore to the other users. The deafen bug was originally found by Yomi95(01G2A32YJDPCF20E7W8RMGR80Z)

Account a(With deafen on) view:
![image](https://user-images.githubusercontent.com/87125939/175167188-516881a8-c194-45db-bbd8-1606c35c1a89.png)

Account b(Cat profile picture) view:
![image](https://user-images.githubusercontent.com/87125939/175167204-df49d837-1bf2-4231-b68c-0c93c38e3537.png)

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
