### ISSUE TITLE
bug: Source code disclosure(May not be a problem)

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#713]
I'm not sure If this is counted as an issue because Revolt is already open source but for those who want to make a rip off version or other private version using Revolt their source code can be seen in public and may lead to further surface attack.

https://app.revolt.chat/assets/RevoltApp.e186d2fc.js.map
https://app.revolt.chat/assets/vendor.e80fdc6a.js.map

**Comment by Evilhotdog** [comment]
I don't think this is an issue? Revite is AGPL, if someone wants to make an alternative version, they can
