### ISSUE TITLE
bug: text input outline clipping. Friends tab "Add Friend" model

### ISSUE THREAD

**Issue by go-compile** [revoltchat/revite#719]
Reproduce: Go to friends tab. Click add friend. Click text input.

![image](https://user-images.githubusercontent.com/97609133/176999437-fa9845ca-bfd1-4030-9b9f-0b8c64c7eeb7.png)

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
