### ISSUE TITLE
feature request: add B Yekan as a font option

### ISSUE THREAD

**Issue by DevEvil99** [revoltchat/revite#724]
### What do you want to see?

its so hard to read persian/farsi and its so bad with default font, please add a new font to it, the "B Yekan" font is free and its good and it should be rtl not ltr

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment]
Is this font truly freely available? I can't find it on Google Fonts or Fontsource

**Comment by Rexogamer** [comment]
There doesn't seem to be anything on that page that indicates that this font is freely available - in addition, it's not really in a format we can easily use

**Comment by DevEvil99** [comment]
hmmmm, can you guys use "Lalezar"? 
link: https://fonts.google.com/specimen/Lalezar

**Comment by Rexogamer** [comment]
Lalezar is licensed under the OFL and is [available via Fontsource](https://fontsource.org/fonts/lalezar), so yes ^^
