### ISSUE TITLE
feature request: Allow users to change font size

### ISSUE THREAD

**Issue by iSaluki** [revoltchat/revite#727]
### What do you want to see?

I have a friend who has a large, hires monitor and struggles to see text and icons easily as Revolt does not scale properly. A simple option to allow changing the size of the interface would greatly ease the experience of using Revolt.

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.
