### ISSUE TITLE
Feature request: Add a talking indicator to voice channels

### ISSUE THREAD

**Issue by iSaluki** [revoltchat/revite#728]
One thing that Revolt is missing is a simple feature that improves QoL on Discord so much. 

On Discord, when somebody is talking a green outline appears around their avatar. If some similar form of indicator was added to Revolt, it would help improve voice accessibility.

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
