### ISSUE TITLE
bug: DM can't be checked or removed

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#731]
If you send someone a message and they don't view it then remove them as a friend & remove the DM channel. If that someone refreshes his Revolt he won't be able to click the DM and It's impossible to remove it unless you can add that someone again.

![image](https://user-images.githubusercontent.com/87125939/178168212-722377af-46af-480e-9962-ff25d5524a7e.png)

**Comment by PierreLGBT** [comment]
I have the same problem, courage

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
