### ISSUE TITLE
feature request: Differentiate Author Ping Messages

### ISSUE THREAD

**Issue by Pysics** [revoltchat/revite#738]
### What do you want to see?

There should be a tiny `@` in the reply if the author ping is turned on:
![image](https://user-images.githubusercontent.com/79257339/179392077-f2e060c1-9add-4fff-a18d-b83754ea4388.png)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Zomatree** [comment]
There is already an `@`:
![image](https://user-images.githubusercontent.com/39768508/179401233-02794691-199d-4568-89c0-d6d4e74fa17e.png)

**Comment by Pysics** [comment]
@Zomatree Are other users able to see it?

**Comment by Rexogamer** [comment]
Yes:
![image](https://user-images.githubusercontent.com/42586271/180310225-e3bb98b1-0949-40dd-9578-45151cfcb62a.png)

I'm going to mark this issue as completed/close it out - if, however, you cannot see the @ symbol, please feel free to reopen this/a new issue as you might've encountered a bug of some kind.
