### ISSUE TITLE
Differentiate hyperlinks in user profiles.

### ISSUE THREAD

**Issue by DeclanChidlow** [revoltchat/revite#745]
In the 'Information' section of user profiles (accessed by clicking on a user's name) hyperlinks look identical to regular text. This makes it hard to identify what is and isn't a link without hovering a mouse over each individual character - something that isn't possible on most mobile phones.

Placing an emphasis effect such as an underline, bold or italic would mitigate this issue.

**Comment by Rexogamer** [comment]
Hyperlinks look distinct to me - what theme are you using?
![D2076AE1-1CAB-4ED8-8209-09A75AF31C67](https://user-images.githubusercontent.com/42586271/181811706-c0f72fd9-e58b-4329-b32d-4bdbf4ca22a2.jpeg)

**Comment by DeclanChidlow** [comment]
I was using the default dark theme. I think it might have been a browser issue as it has stopped after an browser update.
