### ISSUE TITLE
bug: paragraphs are not correctly separating

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#747]
### What happened?

![image](https://user-images.githubusercontent.com/38285861/181919332-e937a521-cffb-4ab0-a866-b6aaa34d9ae4.png)

### Branch

Production (app.revolt.chat)

### Commit hash

[11e8cd6](https://github.com/revoltchat/revite/commit/11e8cd652dfdb20843ebdc70d5faf1d36970b9a6)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Pysics** [comment]
This seems to work after [`07fd598`](https://github.com/revoltchat/revite/commit/07fd598bf9337de0c2073064ebf85e9de663e501).
