### ISSUE TITLE
bug: Creating Channels, Categories, and Servers creates a duplicate.

### ISSUE THREAD

**Issue by KittyKatJas** [revoltchat/revite#748]
### What happened?

When creating a Server, Channel, or Category it will create two of them.
My Browser is the Brave Browser, but this happens everywhere.
It happens on the browser, desktop, mobile.
I am posting a video to show what happens.

https://user-images.githubusercontent.com/73664232/181822675-d4932243-f996-4947-8b21-ad2a70a9d7be.mp4

### Branch

Production (app.revolt.chat)

### Commit hash

11e8cd6

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by bogotesr** [comment]
Also happens on Safari on macOS
