### ISSUE TITLE
bug: Servers and roles duplicating when I create them

### ISSUE THREAD

**Issue by zoofyiscool** [revoltchat/revite#749]
### What happened?

When I'd go to create a server it would create two copies (both completely different).
Same thing would happen when I'd go to create a role, it would create two copies.

How to replicate: [odysee video](https://odysee.com/revoltBug-mp4:4)

Windowing System: X11
Distribution: Gentoo GNU/Linux

**Comment by Slymeball** [comment]
Apparently, [this person](https://github.com/revoltchat/revite/issues/748) is also having issues with this on mobile.

> It happens on the browser, desktop, **mobile.**
-- [KittyKatJas](https://github.com/KittyKatJas), July 30th, 2022

***

I'm only having trouble with it when hitting the enter key. Pressing the button doesn't duplicate it.

https://user-images.githubusercontent.com/51765267/182754366-f6099b61-695b-4e71-a5b1-156affaaa88b.mp4

*Running Arch Linux x64 (GNOME on Wayland), running desktop client on Flatpak.*

**Comment by insertish** [comment]
Fixed in a234e3a582b0ce8dc4266cee55f34faaef116a8d.
