### ISSUE TITLE
bug: Invitation Join/Joined button pops over emote menu.

### ISSUE THREAD

**Issue by D0ON** [revoltchat/revite#751]
To reproduce:
1. Open flatpak client.
2. Send invitation link in a chat.
3. Open up the emote menu.

![invitation_glitch](https://user-images.githubusercontent.com/88665976/182990326-77b61a77-49ca-4b6f-a486-5cdfd0b03cb9.png)

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
