### ISSUE TITLE
Custom Emoji Packs

### ISSUE THREAD

**Issue by aMySour** [revoltchat/revite#755]
Hey,

I love the emoji packs feature in Revolt!
![image](https://user-images.githubusercontent.com/52638772/184511150-bc887c20-9c16-4c2d-9135-36e0d211527b.png)

I was wondering if it'd be possible for there to be some kind of a way to add our own packs here. I'm interesting in getting the Windows 11 3D emojis Microsoft just released in Revolt.

This could be possible by accepting a .zip file with a certain format.

For example:

```
grinning.png
smiley.png

...
```

With each file's name being the emoji name.

I think this would greatly benefit the client!

**Comment by insertish** [comment]
Fluent emoji are coming in the new client.
Other than that this seems like a difficult feature to implement and will only serve to benefit a few users.
