### ISSUE TITLE
bug: context menu doesn't close when scrolling

### ISSUE THREAD

**Issue by TheClashFruit** [revoltchat/revite#757]
### What happened?

The long click context menu doesn't close when scrolling or swiping left or right.

Example:

https://user-images.githubusercontent.com/55049569/184996846-89153920-5213-46b4-998e-6039eda99c54.mp4

### Branch

Production (app.revolt.chat)

### Commit hash

ff41219

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
