### ISSUE TITLE
bug: Cannot apply light mode in PWA

### ISSUE THREAD

**Issue by JapanYoshi** [revoltchat/revite#764]
### What happened?

I tried to use the Default Light theme on my Android "app", but the colors stayed the same.

1. I've tried pressing the "reset" button on theme overrides. Nothing.
2. I've tried applying a different theme, then applying the Default Light theme. No effect; it just keeps the Default Dark theme.
3. I've tried restarting the Revolt client. Nothing.
4. I've tried disabling system-wide dark mode, suspecting that it's interfering with something. Still dark mode in the app.
5. I've tried Force Stopping the app and starting again. No effect.
6. I've cleared the cache and reloaded the app. Still in dark mode.

Meanwhile, with "sync theme" turned on, Revolt Desktop applies Light Mode perfectly fine.

### Branch

Production (app.revolt.chat)

### Commit hash

ff41219

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by JapanYoshi** [comment]
Update: I've also cleared the *browser* cache, force quit the browser app, then restarted Revolt. Still in dark mode.

**Comment by JapanYoshi** [comment]
Found the issue: Kiwi Browser had dark mode enabled in the browser. This is a big argument again a PWA as opposed to a standalone app, React Native style.

**Comment by Rexogamer** [comment]
We can't really solve this as it seems to be a browser issue - as for a more "native" app, we intend to release one at some point but do not currently have any timescales.
