### ISSUE TITLE
bug: 'Danger Zone' text overlapping 'Delete Role' button.

### ISSUE THREAD

**Issue by kyronsaif** [revoltchat/revite#768]
### What happened?

The "Danger Zone" text at the bottom of the Role settings slightly overlaps the Delete Role button.
![Danger Zone text](https://user-images.githubusercontent.com/75399247/187154827-0738fae6-9bf7-498d-8f08-e328daafefc6.PNG)

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.
