### ISSUE TITLE
feature request: Visual Indicator for Users in Voice Chat

### ISSUE THREAD

**Issue by DylanLogan2581** [revoltchat/revite#772]
### What do you want to see?

As far as I can tell at the moment, for both servers and private chats, there is no indication of if/who is currently in a voice call. I think it would be great to have some type of indicator, Such as displaying profile photos or names next to the channel name so that is clear if someone is in a call.

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
