### ISSUE TITLE
bug: "Enable Discord status" off, Discord still stuck reping Revolt

### ISSUE THREAD

**Issue by JapanYoshi** [revoltchat/revite#776]
### What happened?

![gF1Ztw3sEY](https://user-images.githubusercontent.com/8707990/188252447-8da847f1-7ac8-48f3-a755-194e8aad6543.png)
I've turned off the setting "Enable Discord status" (because I prefer to have my status text show up instead of my current game), but Discord is stuck detecting that Revolt is running, and doesn't allow me to delete the "game" from the list.

### Branch

Production (app.revolt.chat)

### Commit hash

ff41219 (Production)

### Desktop

- [X] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
This is not Revolt, Discord mistakenly matches it as a game of a similar name, [Re-Volt](https://store.steampowered.com/app/287310/ReVolt/).

**Comment by JapanYoshi** [comment]
So how do I teach Discord that I’m not playing that?

**Comment by insertish** [comment]
I don't know if there's anyway to force remove it in the Discord client, it's quite stubborn every time I try.
I've heard some people have managed to just change the executable name to avoid this but I don't know if this would then cause issues with auto updating.
