### ISSUE TITLE
Messages won't load after re-entering app

### ISSUE THREAD

**Issue by Forzagod58** [revoltchat/revite#781]
When putting android phone to sleep and entering the app again, new messages don't load

Bug encountered on an s10+ on android 12

**Comment by FelixKLG** [comment]
I can confirm that this bug appears on iOS as well.
The website has to be completely reloaded by either reloading the page or in-case someone used the 'Add to Home Screen' button they'd need to swipe-close the app.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
