### ISSUE TITLE
bug: The search bar itself is the same colour as the sidebar’s background.

### ISSUE THREAD

**Issue by leafpool243** [revoltchat/revite#790]
### What happened?

Expected the search bar to be a different color

Below is what it looks like before you (try to) find the search bar
![image](https://user-images.githubusercontent.com/63614345/191409429-d2d3371b-829a-4444-b31e-31023f143b1c.png)

Below is what it looks like when you’ve clicked on it
![image](https://user-images.githubusercontent.com/63614345/191409467-d7fe9135-2702-4bb3-b6a2-aadd0c2bc4f4.png)

Browser: Brave browser

### Branch

Production (app.revolt.chat)

### Commit hash

40d3356

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
This whole UI will be redesigned.
Closing due to rewrite, https://github.com/revoltchat/frontend.
