### ISSUE TITLE
feature request: Categories permissions & drag channels

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#792]
### What do you want to see?

Same as Discord where you can change a category permissions then It applies to all the channels under it and also to be able to drag channels directly to categories or sort them without going to the server settings.

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
