### ISSUE TITLE
feature request: Forum channel

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#794]
### What do you want to see?

I don't think I need to say much about it but It's like the new Discord feature that they added It's like a channel but forum.

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Infiniticity** [comment]
This has already been suggested in #739.

**Comment by I2rys** [comment]
> This has already been suggested in #739.

Oh I see my bad. Thank you for letting me know.
