### ISSUE TITLE
bug: using + in markdown crashes the app

### ISSUE THREAD

**Issue by OfficialR3ido101** [revoltchat/revite#795]
### What happened?

So When sending one big message only containing + symbols it crashes the app giving the respected error in the screen shot below.

![image](https://user-images.githubusercontent.com/39566484/191650797-f6362df6-e7a1-40bc-8d71-072722a9ae0e.png)

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

[7cf7402](https://github.com/revoltchat/revite/commit/7cf7402cea76b0e6b299ab77b6a5df373cf24de8)

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by brecert** [comment]
Unable to replicate with the latest nightly.
