### ISSUE TITLE
bug: When clicking on the server that you are, the server reloads like it's another one.

### ISSUE THREAD

**Issue by Anachronique** [revoltchat/revite#798]
### What happened?

If you click on a server (on the left panel with the icons) that you're already seeing it's chats, the server reloads like it is another one. I guess it was pretended to do nothing since it's REALLY annoying when you click the server icon by mistake and the chat reloads.

Browser: LibreWolf (Firefox based) but it's a issue on the desktop app too.

### Branch

Production (app.revolt.chat)

### Commit hash

40d3356

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.
