### ISSUE TITLE
bug: When entering server configuration or the general configuration of the app and coming back, the chat flicks (like reloading).

### ISSUE THREAD

**Issue by Anachronique** [revoltchat/revite#799]
### What happened?

The title says by itself, it's really annoying, mainly if you're editing chat permissions or the chats by themselves.

Browser: LibreWolf (Firefox based) but the issue is on the desktop app too.

### Branch

Production (app.revolt.chat)

### Commit hash

40d3356

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
