### ISSUE TITLE
bug: Copying Invite URL only copies the /invite/[code] part

### ISSUE THREAD

**Issue by Andre601** [revoltchat/revite#803]
### What happened?

Right-clicking a Revolt.chat Invite (`https://app.revolt.chat/invite/<code>`) and selecting "Copy Link" only copies the `/invite/<code>` part of it, making it rather difficult to share invites on other sites/platforms.

### Branch

Production (app.revolt.chat)

### Commit hash

[40d3356](https://github.com/revoltchat/revite/commit/40d3356c1ba3569fcc7d73883efda221891542b8)

### What browsers are you seeing the problem on?

Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
