### ISSUE TITLE
bug: text color makes read content look unread

### ISSUE THREAD

**Issue by kiwec** [revoltchat/revite#805]
### What happened?

Default theme. In this screenshot both the category text and the currently selected channel text are way too bright, and look unread.

![2022-10-03-202136_209x138_scrot](https://user-images.githubusercontent.com/1957540/193650339-e1e3be7b-9381-4338-b7c3-463f57d3d59f.png)

Reducing contrast is needed - alternatively (or in addition), you could consider using unread message badges/dots near the channel name.

### Branch

Production (app.revolt.chat)

### Commit hash

40d3356c1ba3569fcc7d73883efda221891542b8

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.

**Comment by Rexogamer** [comment]
The new client has unread indicators (currently exclamation marks, although this will be tweaked)
