### ISSUE TITLE
bug: Revolt's colors

### ISSUE THREAD

**Issue by GhastlySkylie** [revoltchat/revite#807]
### What happened?

they are messed up on mobile and when you select a theme it's darker than usual and the thing that goes to where you click on a server it's fully white on all themes and It's only on mobile (I'm on android)

### Branch

Production (app.revolt.chat)

### Commit hash

This is what it looks like:
![Screenshot_20221008-165310_Samsung_Internet](https://user-images.githubusercontent.com/69837533/194729235-b8a9764e-afd1-4ec4-b9aa-d6218ddce3f1.jpg)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by janderedev** [comment]
Turn off the auto dark mode feature in samsung internet
