### ISSUE TITLE
Pasting large amounts of text into message box freezes Revite

### ISSUE THREAD

**Issue by ehea617** [revoltchat/revite#81]
### Summary
If you paste large amounts of text into the message box, Revite can freeze for multiple seconds or crash entirely. 
### Steps to Reproduce

1. Click on a message input box (Ex. inside Saved Notes)
2. Paste at least 3.7 million characters into the message box
3. Revite will freeze for a few seconds when pasting. If you try to add more into the message box, it will freeze for a few seconds more or crash.

### Potential Fixes

- Set a character limit on the message box that matches the current message character limit.
- Improve performance of TextAreaAutoSize.tsx

### Performance Profile
[Profile-20210815T152846.json.gz](https://github.com/revoltchat/revite/files/6988763/Profile-20210815T152846.json.gz)

**Comment by insertish** [comment]
Fixed in b8c345f493cf9e16efc9d81a59dba657e29c4a3f
