### ISSUE TITLE
bug: Member list being janky in general

### ISSUE THREAD

**Issue by atirut-w** [revoltchat/revite#810]
### What happened?

This, multiple times, on two computers, both on Chrome & Firefox.
![image](https://user-images.githubusercontent.com/25323231/198534001-b18c39a6-1e04-4c97-b9fa-ff26c81601d6.png)

### Branch

Production (app.revolt.chat)

### Commit hash

3836156f3db66e6744b6483643a5a2b488e2584b

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
There are multiple errors in log output, no idea which ones are relevant.
```

### Desktop

- [X] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Moved to https://github.com/revoltchat/revoltchat-solid-client-monorepo/issues/47
