### ISSUE TITLE
Friend call cant unmute 

### ISSUE THREAD

**Issue by Itsredsect** [revoltchat/revite#811]
When I'm on a private call with a friend or in group chats, I can't unmute myself or disable my output.
![grafik](https://user-images.githubusercontent.com/95378207/198707028-e49ba2fb-2539-4aa1-ab38-27ff67da1a2f.png)
![grafik](https://user-images.githubusercontent.com/95378207/198707107-2132a62c-42db-476c-8600-b5f7d51338a7.png)

**Comment by insertish** [comment]
The container can be scrolled, this broke at some point.
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
