### ISSUE TITLE
bug: the keyboard on mobile covers the text box

### ISSUE THREAD

**Issue by GhastlySkylie** [revoltchat/revite#813]
### What happened?

![Screenshot_20221031-051441_Edge](https://user-images.githubusercontent.com/69837533/199082775-bd698d67-699a-42c9-aeb6-ba9d7d4c6396.jpg)
![Screenshot_20221031-051437_Edge](https://user-images.githubusercontent.com/69837533/199082780-20fcb62c-f01a-4860-93c1-1a06c37113a3.jpg)
![Screenshot_20221031-051433_Edge](https://user-images.githubusercontent.com/69837533/199082782-97b1def9-a6c8-4648-b37b-d34d1c600523.jpg)
this happens when you click the text box. this is on android not sure if it's on IOS or not

### Branch

Production (app.revolt.chat)

### Commit hash

3836156

### What browsers are you seeing the problem on?

Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
