### ISSUE TITLE
bug: Channels description is not formatted If long

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#815]
### What happened?

Long descriptions should automatically be flex/formatted so you can see the rest of the content.

### Branch

Production (app.revolt.chat)

### Commit hash

3836156f3db66e6744b6483643a5a2b488e2584b

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None.
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
