### ISSUE TITLE
bug: bad server names

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [revoltchat/revite#821]
### What happened?

Img 1: ![image](https://user-images.githubusercontent.com/61359286/203128322-2003998c-7ca6-4bf5-b364-d7bc40c9b339.png)
Img 2: ![image](https://user-images.githubusercontent.com/61359286/203128532-bc6ffaf1-4d65-4cb4-86f5-f7ac972aab22.png)
Img 3: ![image](https://user-images.githubusercontent.com/61359286/203128609-932ffb67-7380-44f4-b2f6-ce425c692755.png)

You can create servers with emtpy character names (alt + 255) `Img 1`, spaces `Img 2`, and other special characters that shouldnt be available like ☺ (Alt + 1)

### Branch

Production (app.revolt.chat)

### Commit hash

[9be4afe](https://github.com/revoltchat/revite/commit/9be4afe241c56e64944ebde5834569ced7c75334) [(production)](https://github.com/revoltchat/revite/tree/production)
Stable 1.0.1
Native: 1.0.6
API: 0.5.5
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by MrMasrozYTLIVE** [comment]
☻♥♦♣♠•◘○☺◙♂♀♪♫☼►◄↕‼
![image](https://user-images.githubusercontent.com/61359286/203130280-5ee27bf8-5f1b-4f92-90e4-6cbf2d83880d.png)

**Comment by MrMasrozYTLIVE** [comment]
`​` zero width space (`\U+200B` / `&#8203;` / `\200B` - Unicode / Html / Css) 
![image](https://user-images.githubusercontent.com/61359286/203136038-fe72c9db-8406-42ef-bdb4-5b43c85b3e9f.png)

**Comment by insertish** [comment]
Don't see an issue with this, trying to prevent this is probably not worth the time either, emojis are also explicitly allowed and are rendered using chosen emoji pack in the new client.
