### ISSUE TITLE
bug: mobile keyboard and animation

### ISSUE THREAD

**Issue by Mitzingdash** [revoltchat/revite#829]
### What happened?

On android

keyboard: when you have your keyboard open and swipe to the left or to the right the app dosent close the keyboard and makes itself move upwards in the full scale, das not seeing the top half of the app

animation: when you swipe left to the chat and instantly swipe up or down the chat center animation stops das freezing the chat a bit off center

please contact me as i have a screen recording of both bugs

### Branch

Production (app.revolt.chat)

### Commit hash

9be4afe

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
