### ISSUE TITLE
PWA browser blocks JavaScript 

### ISSUE THREAD

**Issue by PeterKW** [revoltchat/revite#831]
Normally on my Android I use Firefox Nightly as my default browser. Revolt, https://fdroid.revolt.chat/repo/chat.revolt.app.twa.apk, seems to be opening the PWA in Brave which is blocking JavaScript. If I wanted PWAs to use Firefox by default is that at all possible?
Thank you very much!

![Screenshot_20221224-180816.png](https://user-images.githubusercontent.com/13779157/209447287-fc7ce749-972c-4de4-a08e-1c093ff9c689.png)

**Comment by Rexogamer** [comment]
This sounds like a browser issue - while Firefox Desktop doesn't support PWAs, I'm pretty sure FF Android does. There might be a device setting for this? Either way, I'm closing this issues as it isn't an issue with Revite itself.
