### ISSUE TITLE
bug: Fails to reconnect after internet connection interrupted

### ISSUE THREAD

**Issue by vertigo220** [revoltchat/revite#833]
### What happened?

With other online apps, including Discord, when I lose internet connection and the apps therefore lose connection, once the internet connection is reestablished, the apps will also reestablish connection. Revolt, however, did not do so, and hours after an interruption it was still showing me as offline. I had to restart it to get it working. This is with the app, not the browser (not sure if this should be in this repo or the one specific to that; also not sure about the desktop checkbox below as it says the issue is specific to Revolt Desktop yet *not* with Revolt Desktop).

### Branch

Production (app.revolt.chat)

### Commit hash

[9be4afe](https://github.com/revoltchat/revite/commit/9be4afe241c56e64944ebde5834569ced7c75334)

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
