### ISSUE TITLE
bug: "Voice connected" when "calling" offline contact

### ISSUE THREAD

**Issue by vertigo220** [revoltchat/revite#834]
### What happened?

If I "call" (calling doesn't work, but when I press the call button) my friend when he's offline, it will still "connect" (says "Voice connected") which shouldn't happen since he's not there to answer. This is with the desktop app.

### Branch

Production (app.revolt.chat)

### Commit hash

[9be4afe](https://github.com/revoltchat/revite/commit/9be4afe241c56e64944ebde5834569ced7c75334)

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
