### ISSUE TITLE
Gradient Role Color Not Updated On Member Settings

### ISSUE THREAD

**Issue by DeMoN100** [revoltchat/revite#836]
### What happened?

Bromite/brave browser mobile
This happens on the pwa & desktop client as well.
![AFFIX_20230128_173616](https://user-images.githubusercontent.com/8564572/215294501-cbc3c154-5d1e-49ea-ae57-d13a68b7a6e1.jpg)
When changing gradient role colors multiple times the updated displays on the server memberlist. But in server settings when viewing the members list in settings the gradient roles display in the original gradient applied.

### Branch

Production (app.revolt.chat)

### Commit hash

9be4afe

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Hey! I've closed this due to the ongoing rewrite - however, I've marked it as something to look out for in the rewrite by linking it to revoltchat/frontend#134.
