### ISSUE TITLE
bug: Rounded corner on discover page.

### ISSUE THREAD

**Issue by CarlTheObeseCat** [revoltchat/revite#846]
### What happened?

Not to be rounded on the discover page this is a tiny nitpick. (Top left corner)

### Branch

Production (app.revolt.chat)

### Commit hash

21175df

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Closing as wontfix due to rewrite; this is a very minor issue that will likely be picked up when we add Discover to the new client.
