### ISSUE TITLE
add screen share

### ISSUE THREAD

**Issue by Lil-auxi** [revoltchat/revite#854]
### What do you want to see?

hello everyone i would like to tell you that i love your app besides everything in Revolt Chat i will need this particular thing that is adding screen share i would like to watch with my friends.

thank you everyone 

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment]
Closing as a duplicate of revoltchat/vortex#4, which is on hold due to the voice server rewrite.

**Comment by alexanderjuliao** [comment]
PLS!
