### ISSUE TITLE
bug: When a user is kicked from a server while in a voice chat, they remain in the voice chat

### ISSUE THREAD

**Issue by InsaneWaifu** [revoltchat/revite#855]
### What happened?

Example one:
![image](https://user-images.githubusercontent.com/41633170/225726053-d16ff59d-a202-4523-8bac-9aa65872757d.png)
Here you can see three users in a voice chat in a revolt server (not Revolt Lounge)
![image](https://user-images.githubusercontent.com/41633170/225726313-443fc4ea-2f79-4d00-89eb-0fa7d6d5e7bf.png)
Here you can see that this user is not in this server, as they were banned.

My friend was able to reproduce this by kicking me from a server while I was in the voice channel

### Branch

Production (app.revolt.chat)

### Commit hash

e17e556

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
From what I know, this is an issue with Vortex (the voice server) - closing due to its ongoing rewrite.
