### ISSUE TITLE
bug: Roles not updating to members

### ISSUE THREAD

**Issue by DiamondBuff** [revoltchat/revite#863]
### What happened?

Follow the steps provided in this gif: 

![NVIDIA_Share_zAfsA3gLGP](https://user-images.githubusercontent.com/128391086/226372094-9c9842fe-ee11-475f-938b-2d9607e27e53.gif)

### Branch

Production (app.revolt.chat)

### Commit hash

![firefox_b1BuzHdsQy](https://user-images.githubusercontent.com/128391086/226372158-f54604e0-6154-4b70-aa31-f8bedbe8886f.png)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Try scrolling down and clicking the Save button - if this doesn't work, please leave a comment:
![0FFA4A6F-5FED-4AA6-8E6D-B64D13CB00D2](https://user-images.githubusercontent.com/42586271/226961039-c131b3cc-3d60-4652-a7dd-d49ed2609c16.jpeg)
