### ISSUE TITLE
bug: Revolt does not open on computer login. Instead opens Electron placeholder

### ISSUE THREAD

**Issue by searinminecraft** [revoltchat/revite#874]
### What happened?

When the 'Start with computer' option is enabled in desktop settings, on login, it opens the placeholder Electron app instead of Revolt. (Don't know if it also happens on Windows/macOS)

![image](https://user-images.githubusercontent.com/114207889/229337606-ce6246c4-19a6-42e3-9d0e-93857cef9a57.png)

# Information:

* OS: Artix Linux
* Kernel: 6.2.8-zen1-1-zen
* Where I got Revolt from: AUR

### Branch

Production (app.revolt.chat)

### Commit hash

e17e556 (master)

### Desktop

- [X] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Wrong repository; thus should be transferred to revoltchat/desktop.
