### ISSUE TITLE
bug:  Can't See A Group Chat Call

### ISSUE THREAD

**Issue by overvalue** [revoltchat/revite#887]
### What happened?

If a person in the group chat starts a video call you can't see it , you only get to know if you join the call
 Call Started From Alt 
![image](https://github.com/revoltchat/revite/assets/121876198/3df09204-8e5e-45e1-8ffe-a9aee6af73b6)
Call Can't Be seen
![image](https://github.com/revoltchat/revite/assets/121876198/067e3d54-922b-45be-a6e2-63cedf6213f8)

### Branch

Production (app.revolt.chat)

### Commit hash

idk.

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Not a bug; this is a missing feature, and iirc relies on the upcoming voice rewrite

**Comment by overvalue** [comment]
Ohk
