### ISSUE TITLE
bug: cannot change avatar or banner

### ISSUE THREAD

**Issue by derpguy125** [revoltchat/revite#892]
### What happened?

Tried to change my avatar and banner, got a network error.

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

9bc052e

### Relevant log output

```shell
Access to XMLHttpRequest at 'https://autumn.revolt.chat/avatars' from origin 'https://app.revolt.chat' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
autumn.revolt.chat/avatars:1
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Autumn (our file server) is currently experiencing an outage - once this has been resolved, you should be able to upload images without any issues.
