### ISSUE TITLE
feature request: edit role /Edit category 

### ISSUE THREAD

**Issue by UndraStill** [revoltchat/revite#910]
### What do you want to see?

The revolt role system is not very easy to use I would like a way to manage roles like on discord version 126.21

It would be cool to be able to change the permissions of all the rooms by changing only those of the category It would be cool to be able to change the permissions of all the rooms by changing only those of the category 

### PWA

- [X] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment]
Closing due to client rewrite.
