### ISSUE TITLE
bug: Unable to Reset password in Divolt

### ISSUE THREAD

**Issue by Pocarai** [revoltchat/revite#914]
### What happened?

I can't able to reset my password. It say's **OperationFailed** in the divolt.xyz/login/reset.
I need to reset my account password since I forgot it right away

### Branch

Production (app.revolt.chat)

### Commit hash

Sorry, it's my first time to report my Problem

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Not an issue with Revite/Revolt - please contact the Divolt team for assistance.
