### ISSUE TITLE
bug: Text shows up multiple times on Revolt web 

### ISSUE THREAD

**Issue by anomaletix** [revoltchat/revite#915]
### What happened?

This is actually a few issues in one; so I will put them accordingly.

1. On startup, some parts of the UI will bug out and show themselves multiple times.
[revoltbuyg2](https://github.com/revoltchat/revite/assets/88979751/3b48a1ce-d781-4ad3-b48a-a89fc7b1ec37)
![revoltbug1](https://github.com/revoltchat/revite/assets/88979751/df5b3ad3-182e-49ad-ad96-4d04e9fb0efc)
![revoltbug3](https://github.com/revoltchat/revite/assets/88979751/7dd715ce-25f7-4d49-a775-529510b4ac77)
This bug makes certain things (ex: Role names or the "Welcome to REVOLT" screen) appear multiple times.

2. Hovering over a user's name/message in chat will cause it to duplicate itself. You can do this multiple times.

![revoltbug4](https://github.com/revoltchat/revite/assets/88979751/7ffa6afd-6162-43e4-9d88-dcb537bb4f20)

The usernames reset after re-opening the server.

3. Clicking on buttons on the main user menu and settings causes it to duplicate.

![revoltbug5](https://github.com/revoltchat/revite/assets/88979751/c9a95958-48b5-400c-a918-4a90c4ab80ca)
Pre-clicking on the menu buttons
![revoltbug6](https://github.com/revoltchat/revite/assets/88979751/b8384e12-2a8d-414b-9c03-2b7e8770e854)
Post-clicking on the menu buttons

The same issue is present in the Settings.
![revoltbug7](https://github.com/revoltchat/revite/assets/88979751/ae3e01ed-aa26-4ef6-a2e9-cdd8b7d9384a)

### Branch

Production (app.revolt.chat)

### Commit hash

9d83d7c

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
I've never encountered this locally - are you using any plugins, browser extensions or user scripts?

**Comment by anomaletix** [comment]
So I learnt this was caused by an extension I had called Bionic Reader, which kept trying to update text that is always changing meaning it duplicated.
