### ISSUE TITLE
bug:  XXX cannot be used as a JSX component.

### ISSUE THREAD

**Issue by wizardAEI** [revoltchat/revite#918]
### What happened?

<img width="765" alt="Screenshot 2023-07-19 at 22 40 09" src="https://github.com/revoltchat/revite/assets/61337085/65d06080-8485-475d-af08-30358c7da8bd">

```
App' cannot be used as a JSX component.
  Its type '() => Element' is not a valid JSX element type.
    Type '() => Element' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'Element' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.ts(2786)
```

### Branch

Production (app.revolt.chat)

### Commit hash

e8de3bca65bdfc355003e4b5d2669da9f7788639

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
Revite is largely on a code freeze and further development is unlikely/will be limited - however, is this still an issue?

**Comment by Rexogamer** [comment]
Closing as this is a minor typing issue.
