### ISSUE TITLE
Show animated profile pictures on message hover/tap

### ISSUE THREAD

**Issue by RavingGrob** [revoltchat/revite#92]
While you can upload and see an animated profile picture in someone's bio, in the chat it's unapparent.

**Comment by insertish** [comment]
I believe avatars should appear be animating on hover?

What browser are you using?

**Comment by RavingGrob** [comment]
That's my bad, it appears it doesn't animate in the top left or in the "My Account" page at all I do see it animating on hover elsewhere

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
