### ISSUE TITLE
Entrance for guests.

### ISSUE THREAD

**Issue by comomberchese** [revoltchat/revite#931]
### What do you want to see?

Hello. I think the entrance for guests will increase the attendance of Revolt.

Thanks.

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment]
What do you mean? Are you referring to more varied welcome messages? Welcome stickers? Something else?

**Comment by comomberchese** [comment]
Entering the chat without an email and password, entering only the login.

The possibility of guest entry is available in many web chats.
