### ISSUE TITLE
feature request: add spoilers in chats to hide words

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#934]
### What do you want to see?

please add spoilers so people can hide words by putting || on the start and end of the words they want to hide, and then other people can toggle their visibility by clicking on them

the image below shows an example of where the || should go to hide all the words between the lines, and the video below shows what the spoilers should look like

![IMG_6560](https://github.com/revoltchat/revite/assets/111091825/da294453-4ee3-494e-a179-7112ac9f6650)

https://github.com/revoltchat/revite/assets/111091825/3d5da122-44a0-4960-b2c0-c8ba5909e41b

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment]
We already support signatures - however, you'll need to use !! instead.

**Comment by pinkjimrussiagirl** [comment]
> We already support signatures - however, you'll need to use !! instead.

ok, i thought it was same as discord and guilded with the “||” but now i know that revolt uses “!!”

anyways have you looked at my feature request about the user tags/discriminators about having the ability to change them so people can have it set to a favorite number or use the same number as on their discord account if they used discord before

**Comment by Rexogamer** [comment]
https://github.com/revoltchat/revite/issues/936#issuecomment-1703866976
