### ISSUE TITLE
feature request: add these following features (read description)

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#935]
### What do you want to see?

please add the following features i have listed below

- make an ios app so ios users don’t have to use the browser app when they want to use the app
- redesign the way the channels and categories are made so that it’s more like discord
- add user profile cards instead of taking them straight to the user profile, and they can click on the user’s profile image to take them to the user profile
- add user profile cards in the right hand sidebar of dm chats (except for dm groups)
- add an option to have the server and chat list in the default layout or have it in a ios style home screen layout similar to discord
- add an option for gradients in the theme colors and role colors
- add an option to add role icons to server roles
- fix the server icon and banner not being animated when in a server that has them
- add an option for users to add multiple accounts without having to sign out to switch accounts
- add the ability for users to change the status icon shapes using css
- add the option to create permissions for a category without having to waste time adding permissions to each channel separately
- add the option for users to change the nickname and server profile of themselves and other people
- add the ability for people to stream their camera and share their screen in voice channels on both mobile and desktop
- add the ability to create more types of channels such as media channels, forum channels, document channels, announcement channels, rules channels, calendar channels, schedule channels and checklist channels
- redesign the message box for browsers
- add more options to add in messages such as gifs, voice record, polls, forms and other types of files that aren’t images
- fix the custom emojis so people can send custom emojis just by typing the name such as “:pinkybee:” for a PinkJimRussiaGirl head without having to ender the emoji id number to be able to send it
- add the ability to add roles to members by right clicking on them in the member list of a server
- add the ability to add server groups without having to create separate servers for each thing

i cannot think of anything else at this point that should be added so please add all these

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment]
Revite is currently in maintenance mode and won't be receiving any major updates - in addition, several of these suggestions are not feasible or would require wider work.
