### ISSUE TITLE
feature request: add ability to change user tag

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#936]
### What do you want to see?

please add the ability to change the user tag so users can change it to whatever number they want from 0001-9999 like on discord

![IMG_6564](https://github.com/revoltchat/revite/assets/111091825/714ff190-6368-49a1-bd0a-4b783a99a037)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment]
This is not a Revite issue - in addition, we have previously declined this suggestion, although we may reconsider this decision in future.
