### ISSUE TITLE
bug: unable to delete channels on ios

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#938]
### What happened?

usually when i hold down on a channel it will show a pop up saying if i want to edit or delete the channel, but on ios it’s only saying to create a new channel or category
![IMG_6774](https://github.com/revoltchat/revite/assets/111091825/2959741e-6c16-446f-b3b1-ed3fcc7682d2)

also please bring out an ios app now because its unfair for ios users that there’s an app for desktop and android but no ios app

### Branch

Production (app.revolt.chat)

### Commit hash

![IMG_6775](https://github.com/revoltchat/revite/assets/111091825/892ac712-d2e7-4ed4-95b8-d053df7e4b06)

### What browsers are you seeing the problem on?

Safari

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
- For the last time, **please stop making unrelated requests in issues.**
- The Android app isn't out yet either, and an iOS app is in development.
- Closing due to client rewrite.

**Comment by pinkjimrussiagirl** [comment]
> * For the last time, **please stop making unrelated requests in issues.**
> * The Android app isn't out yet either, and an iOS app is in development.
> * Closing due to client rewrite.

idk what requests is related

**Comment by Rexogamer** [comment]
The second part of your issue.

**Comment by pinkjimrussiagirl** [comment]
> The second part of your issue.

ok, also i’m thinking of making my own chat app which will be a lot like discord with all the same layouts and status icons, but sadly i am very bad at coding, and it will have a custom theme designer like revolt but where it won’t directly copy the features from discord and revolt and guilded

**Comment by pinkjimrussiagirl** [comment]
> The second part of your issue.

can you look on my help request about custom themes about how to change the status icon shapes
