### ISSUE TITLE
issue: cannot leave channel, android app and copy function not work,

### ISSUE THREAD

**Issue by Unacceptium** [revoltchat/revite#939]
### What happened?

issue1 (solved)
cannot leave a channel
android browser version: long clicking the server icon makes the browser ask for open a new page, and revolt long click does not takes, it drags the icon instead. tried in Fulguris, Ninja, ADM.

issue2 (solved)
app not work
android app (both gplay and fdroid version) does not launch, instead redirect to browser

issue3 
website version "copy text" function does nothing

### Branch

Production (app.revolt.chat)

### Commit hash

-

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Unacceptium** [comment]
at first, my english is bad
sorry for title miswrite but my wifi bad

**Comment by Unacceptium** [comment]
@lo-kiss thanks for reply.

**Comment by Rexogamer** [comment]
Regarding number 3, can you provide more information about your browser?

**Comment by Unacceptium** [comment]
@Rexogamer yes
https://f-droid.org/packages/net.slions.fulguris.full.fdroid/
https://github.com/mthli/Ninja
https://play.google.com/store/apps/details?id=com.dv.adm&hl=en_US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dadm&pcampaignid=APPU_1_K_kRZf3nBL2d4-EPrtiKqAM
