### ISSUE TITLE
bug: autocomplete keeps removing blur

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#943]
### What happened?

i am making a custom css theme and i am trying to add where the autocomplete box is transparent and has a blur, but on mobile the blur keeps disappearing no matter what i set the blur to

![IMG_7059](https://github.com/revoltchat/revite/assets/111091825/adf12705-47e0-4786-8280-962f106833d1)
![IMG_7060](https://github.com/revoltchat/revite/assets/111091825/f58f0c11-d9f9-44eb-b439-d9a313230d3c)

note: i already know that this won’t be fixed because it’s not a **critical bug** with revolt because i’ve seen other discussions that said you only fix bugs that are absolutely critical

### Branch

Production (app.revolt.chat)

### Commit hash

![IMG_7009](https://github.com/revoltchat/revite/assets/111091825/5d2d72ae-143d-47a1-8895-7c860034e229)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by pinkjimrussiagirl** [comment]
wtf no one replied about why it was closed for no reason

**Comment by Rexogamer** [comment]
> note: i already know that this won’t be fixed because it’s not a **critical bug** with revolt because i’ve seen other discussions that said you only fix bugs that are absolutely critical

You said it yourself 🤷‍♀️
