### ISSUE TITLE
bug: unable to use revolt at all

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#944]
### What happened?

when i opened up revolt just now it’s starting to say an error as if i’m not connected to the internet

i have checked my internet settings and nothing is wrong with them so i think the entire revolt server is shut down

closed-source chat places wouldn’t have this problem as they’re run by massive companies

### Branch

Production (app.revolt.chat)

### Commit hash

unable to get it since revolt is down completely

### What browsers are you seeing the problem on?

Safari

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment]
We're aware of the issue and are investigating right now. Please stop trying to defend closed source software. Thanks for your patience.

**Comment by pinkjimrussiagirl** [comment]
> We're aware of the issue and are investigating right now. Please stop trying to defend closed source software. Thanks for your patience.

idk what you meant about “trying to defend closed source stuff”
