### ISSUE TITLE
Dialogue box to leave server causes client to freeze(?)

### ISSUE THREAD

**Issue by cyrus01337** [revoltchat/revite#95]
### Summary
Upon leaving a server the dialogue box pops up, but the leave option appears grayed out. Upon clicking it, it does not close and stays frozen which requires a refresh - upon doing so, it seems that I HAVE left the server but the only way I was able to tell was through a refresh.

### Evidence
![image](https://user-images.githubusercontent.com/63274991/129718926-d42baecb-19aa-4403-b417-b398938c4d47.png)

##### Windows
Edition	Windows 10 Home
Version	21H1
Installed on	‎29/‎06/‎2020
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

##### Revolt
Revolt - MS Store Desktop Client

745b034 (master)
Nightly 1.0.0-vite
Native: 1.0.0
API: 0.5.2-alpha.1
revolt.js: 5.0.1-alpha.6-patch.0

**Comment by insertish** [comment]
Reproduced, thank you for the report.

![image](https://user-images.githubusercontent.com/38285861/129786935-8be292fd-9ca7-40c4-b396-7295a8c347de.png)cccccct
