### ISSUE TITLE
bug: You were (not) signed out! 

### ISSUE THREAD

**Issue by Unacceptium** [revoltchat/revite#954]
### What happened?

anything similar never happened to me. i don't use any VPN or proxy with this browser, or even ad blockers.

-i opened web version of Revolt.
-popup said You were signed out! with login screen background
-i did a webpage refresh
-cloudfare did a you are not a robot test wich failed for 8 mins
-refreshing page
-Revolt acted like nothing happened and continue as always‽

extra
browser: Fulguris by Slions

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

[782a9b5](https://github.com/revoltchat/revite/commit/782a9b54ba727418e39b86fd6f5a9678eec800d2) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 1.0.1
API: 0.6.6
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Relevant log output

```shell
N/A
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by amycatgirl** [comment]
Revolt is currently suffering an outage but yeah, that's weird. (Source: https://status.revolt.chat)

**Comment by Unacceptium** [comment]
@amycatgirl uh! but its ok after that happened like everything loads...

**Comment by Unacceptium** [comment]
revolt full died
"Bad gateway Error code 502"

**Comment by Rexogamer** [comment]
Closing as this outage was resolved.
