### ISSUE TITLE
A11Y Unlabeled Images

### ISSUE THREAD

**Issue by stormdragon2976** [revoltchat/revite#963]
There are several links at the top of the page with unlabeled images. This means screen readers can not tell what the link actually does. They are near the part that says "Press spacebar to start a drag..." There is another just after "CONVERSATIONS" but it appears to just be an image, I don't think it is clickable.

For images that would be considered decorative, as in they do not control features, use alt="" to hide them. There is another at a heading level 3 that reads "Welcome to (unlabeled image)."

**Comment by Rexogamer** [comment]
Closing due to the client rewrite where we're giving accessibility more of a focus - I'll link this issue so we know to keep this in mind.
