### ISSUE TITLE
feature request: 

### ISSUE THREAD

**Issue by Trido56** [revoltchat/revite#964]
### What do you want to see?

I want them to add my emoji, I will be very glad if you accept their names NovaEmoji
here is the download link https://drive.google.com/drive/u/0/folders/13FGUvupD_1wmaCb7aBCipfuBGuSRn2VJ (they are still in beta)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by insertish** [comment]
We're not looking to add any further emoji packs currently, and those that we do add must have significant coverage.
