### ISSUE TITLE
Emoji upload bug:

### ISSUE THREAD

**Issue by Fritzuwu** [revoltchat/revite#965]
### What happened?

I am using the latest Android version. I had tried uplaoding emojis to a server, but I am met with an error message of "An error occured." and "Network error." After I try to select an image.

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

5b6546b

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Likely temporary failure with remote.
