### ISSUE TITLE
Number inside Ping circle is not centered

### ISSUE THREAD

**Issue by ppotatoo** [revoltchat/revite#97]
![image](https://user-images.githubusercontent.com/76911441/129732965-750087e8-2f62-49f0-95c9-e5fe16c0f027.png)
Using Firefox 91.0

**Comment by ppotatoo** [comment]
here it is on chrome: 
![image](https://user-images.githubusercontent.com/76911441/129733724-5dce6c9c-4ffb-41e3-9248-18f112770c25.png)

**Comment by insertish** [comment]
Fixed in 66e946f0fc9172da626aac8f1674d67d0d6dbdbe
