### ISSUE TITLE
bug: Servers down, i am pissed off

### ISSUE THREAD

**Issue by manaphychu** [revoltchat/revite#972]
### What happened?

I kept getting constant errors like something bad happened and telling me to see the console, IT SUCKED! I Blame CloudFlare over the server issues!

### Branch

Production (app.revolt.chat)

### Commit hash

[0f0808a](https://github.com/revoltchat/revite/commit/0f0808aa5637be5475f28e09f8f4d2617b6df2ae)

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [X] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by Zomatree** [comment]
This is the wrong repository for reporting this, furthermore this is not an issue coming from cloudflare, it’s a server issue with Revolt.
