### ISSUE TITLE
bug: OTP codes not being sent for new users

### ISSUE THREAD

**Issue by DilanRona** [revoltchat/revite#980]
### What happened?

Tried to get a friend to join Revolt. Not getting otp verification code sent to email, when registering on the mobile client and website. To my knowledge he is using Windows 11, not sure what browser he was using at the time. Might have been chrome.

### Branch

Production (app.revolt.chat)

### Commit hash

n/a

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
We do not have OTP login via email, not sure what this is referring to?

**Comment by DilanRona** [comment]
The OTP code is supposed to be sent to the phone right? Well he is not getting any OTP codes.

    On Sunday, 29 September 2024 at 15:55:06 GMT+2, Paul Makles ***@***.***> wrote:  
 
 


We do not have OTP login via email, not sure what this is referring to?

**Comment by insertish** [comment]
That's also not a thing.
Revolt's OTP requires the use of an authenticator app which provides the codes on demand.

Please ask them to email in at contact@revolt.chat to get help from someone on the support team.
