### ISSUE TITLE
bug:  ScrollToBottom is broken

### ISSUE THREAD

**Issue by coleishere2225** [revoltchat/revite#981]
### What happened?

After logging in and cllicked the chat group it doesn't scroll to the bottom when going to the text channel of the latest messages at most of the time using Firefox or a fork of Firefox. 

Also, The scrolltobottom function sometimes work in Google's browser rendering engine and other times, it don't.

As I looked around for app.revolt.chat forks in this repository a few months ago and tested rolt.chat, I've noticed the ScrollToBottom function was working flawlessly around in 2023 as for the older version when Revite's codebase was updated last.

(I blurred the chat timeline out of my Roleplay chat group for privacy reasons, I couldn't get to demonstrate how the bug happens off my other Revolt group that is semi roleplay and gamer ~~based~~ focused that has my identity in it unlike the main Revolt group in this clip because the timeline was sending me to the bottom after login.)

https://github.com/user-attachments/assets/dede65f7-50b1-47b2-a990-59d8989fb40f

### Branch

Production (app.revolt.chat)

### Commit hash

[00e6ead](https://github.com/revoltchat/revite/commit/00e6ead9bd6ed84ecc3b8538e9c271102f7353df) [(master)](https://github.com/revoltchat/revite/tree/master)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by coleishere2225** [comment]
A follow up from earlier where I mentioned that I couldn't get to demonstrate how the bug happens on my semi rolepaly and gamer focused Revolt group, while I was recording the other clip of my other Revolt group, I mess up by opening the wrong program that had nothing to do with ending the recording. 

And, this is the clip where the timeline sends me to the bottom just because it was my latest message from a year ago. 

https://github.com/user-attachments/assets/3c53dd8d-783e-43b7-99df-51b49cac9133

**Comment by insertish** [comment]
Message renderer in https://github.com/revoltchat/frontend is much more stable, closing as WONTFIX since this project is now deprecated.
