### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by Quibe222** [revoltchat/revite#991]
### What happened?

settings and permissions dont save, voice dont work

### Branch

Production (app.revolt.chat)

### Commit hash

[?](https://github.com/revoltchat/revite/commit/?) [(?)](https://github.com/revoltchat/revite/tree/?)
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment]
assuming this was posted twice (#990) in error
